(function(){
const PROXY='https://fihyzcabvrndsztlsufg.supabase.co/functions/v1/product-image-proxy';
let logoBmp=null;
async function logo(){if(logoBmp)return logoBmp;const b=await fetch('assets/vent-it-logo.webp').then(r=>r.blob());logoBmp=await createImageBitmap(b);return logoBmp}
function comps(data,w,h){const m=new Uint8Array(w*h),seen=new Uint8Array(w*h),out=[];for(let i=0;i<w*h;i++){const j=i*4,r=data[j],g=data[j+1],b=data[j+2],a=data[j+3];if(a>80&&r>105&&r-g>24&&r-b>24&&r>g*1.18&&r>b*1.15)m[i]=1}for(let k=0;k<m.length;k++){if(!m[k]||seen[k])continue;const st=[k];seen[k]=1;let n=0,minx=w,miny=h,maxx=0,maxy=0;while(st.length){const q=st.pop(),x=q%w,y=(q/w)|0;n++;minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);for(const z of [q-1,q+1,q-w,q+w])if(z>=0&&z<m.length&&!seen[z]&&m[z]&&Math.abs((z%w)-x)<=1){seen[z]=1;st.push(z)}}if(n>=3)out.push({n,minx,miny,maxx,maxy,cx:(minx+maxx)/2,cy:(miny+maxy)/2})}return out.sort((a,b)=>b.n-a.n)}
function cluster(cs,w,h){const top=cs.slice(0,18);let best=null;for(const seed of top){let g=[seed],change=true;while(change){change=false;for(const c of top){if(g.includes(c))continue;if(g.some(x=>Math.abs(c.cy-x.cy)<h*.09&&Math.abs(c.cx-x.cx)<w*.24)){g.push(c);change=true}}}const minx=Math.min(...g.map(x=>x.minx)),maxx=Math.max(...g.map(x=>x.maxx)),miny=Math.min(...g.map(x=>x.miny)),maxy=Math.max(...g.map(x=>x.maxy)),n=g.reduce((a,x)=>a+x.n,0),bw=maxx-minx+1,bh=maxy-miny+1,ratio=bw/Math.max(1,bh);if(ratio<1.2||ratio>12||bw>w*.55||bh>h*.28)continue;const score=n*(1+Math.min(ratio,5)*.15);if(!best||score>best.score)best={minx,maxx,miny,maxy,score}}return best}
function angle(data,w,h,b){const pts=[];for(let y=b.miny;y<=b.maxy;y++)for(let x=b.minx;x<=b.maxx;x++){const i=(y*w+x)*4,r=data[i],g=data[i+1],bb=data[i+2],a=data[i+3];if(a>80&&r>105&&r-g>24&&r-bb>24&&r>g*1.18&&r>bb*1.15)pts.push([x,y])}if(pts.length<5)return 0;let mx=0,my=0;for(const q of pts){mx+=q[0];my+=q[1]}mx/=pts.length;my/=pts.length;let xx=0,yy=0,xy=0;for(const q of pts){const dx=q[0]-mx,dy=q[1]-my;xx+=dx*dx;yy+=dy*dy;xy+=dx*dy}let a=.5*Math.atan2(2*xy,xx-yy);return Math.max(-.8,Math.min(.8,a))}
function erase(ctx,b,aw,ah,W,H){const sx=W/aw,sy=H/ah;let x0=Math.max(0,Math.floor(b.minx*sx)-4),x1=Math.min(W-1,Math.ceil((b.maxx+1)*sx)+4),y0=Math.max(0,Math.floor(b.miny*sy)-4),y1=Math.min(H-1,Math.ceil((b.maxy+1)*sy)+4);const im=ctx.getImageData(0,0,W,H),d=im.data,mw=x1-x0+1,mh=y1-y0+1,mask=new Uint8Array(mw*mh),red=(r,g,b,a)=>a>80&&r>105&&r-g>24&&r-b>24&&r>g*1.18&&r>b*1.15;for(let y=0;y<mh;y++)for(let x=0;x<mw;x++){const X=x0+x,Y=y0+y,i=(Y*W+X)*4;if(red(d[i],d[i+1],d[i+2],d[i+3]))mask[y*mw+x]=1}for(let y=0;y<mh;y++){let f=-1,l=-1;for(let x=0;x<mw;x++)if(mask[y*mw+x]){if(f<0)f=x;l=x}if(f<0)continue;const Y=y0+y,li=(Y*W+Math.max(0,x0+f-6))*4,ri=(Y*W+Math.min(W-1,x0+l+6))*4,L=[d[li],d[li+1],d[li+2]],R=[d[ri],d[ri+1],d[ri+2]];for(let x=f;x<=l;x++){if(!mask[y*mw+x])continue;const t=(x-f)/Math.max(1,l-f),i=(Y*W+x0+x)*4;d[i]=L[0]*(1-t)+R[0]*t;d[i+1]=L[1]*(1-t)+R[1]*t;d[i+2]=L[2]*(1-t)+R[2]*t;d[i+3]=255}}ctx.putImageData(im,0,0);return{x:x0,y:y0,w:x1-x0+1,h:y1-y0+1}}
async function process(img,p){try{const u=new URL(PROXY);u.searchParams.set('sku',p.sku);u.searchParams.set('model',p.model);u.searchParams.set('category',p.category||'');const blob=await fetch(u).then(r=>r.blob()),bmp=await createImageBitmap(blob),W=bmp.width,H=bmp.height,c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.drawImage(bmp,0,0);const aw=Math.min(300,W),ah=Math.round(H*aw/W),ac=document.createElement('canvas');ac.width=aw;ac.height=ah;const ax=ac.getContext('2d',{willReadFrequently:true});ax.drawImage(c,0,0,aw,ah);const dat=ax.getImageData(0,0,aw,ah).data,b=cluster(comps(dat,aw,ah),aw,ah);if(b){const a=angle(dat,aw,ah,b),cl=erase(ctx,b,aw,ah,W,H),lg=await logo(),asp=lg.width/lg.height;let lw=Math.min(W*.28,Math.max(cl.w*1.08,cl.h*asp)),lh=lw/asp;if(lh>H*.11){lh=H*.11;lw=lh*asp}const cx=cl.x+cl.w/2,cy=cl.y+cl.h/2;ctx.save();ctx.translate(cx,cy);ctx.rotate(a);ctx.drawImage(lg,-lw/2,-lh/2,lw,lh);ctx.restore()}img.src=c.toDataURL('image/webp',.9)}catch(e){console.warn('brand image',e)}}
window.VentBrandImage=process;
})();