function installVentAuto(){
 const A=VentPlanAuto,G=VentPlanGeometry,R=VentPlanReliability;let running=null,sequence=0;
 const lt=(a,b,c)=>state.lang==='lt'?a:state.lang==='no'?(c||b):b;
 const area=document.createElement('section');area.id='autoPlanStatus';area.className='reliabilityBar';area.setAttribute('role','status');area.setAttribute('aria-live','polite');document.getElementById('reliabilityBar').before(area);
 const styles=document.createElement('style');styles.textContent='.autoStages{display:flex;gap:6px;flex-wrap:wrap}.autoStages span{background:#edf6f8;border-radius:6px;padding:5px 8px;font-size:11px}.autoIssue{color:#8a4820}#autoPlanStatus:empty{display:none}';document.head.append(styles);
 const oldT=t;t=function(k){if(k==='bgLoaded')return lt('Brėžinys įkeltas. Automatinis apdorojimas prasideda.','Drawing loaded. Automatic processing starts.');if(k==='uploadInfo')return lt('Įkelk vieno aukšto PDF arba nuotrauką. Planeris automatiškai išskirs brėžinį, perskaitys užrašus ir nubraižys atpažintas patalpų ribas. Trūkstami pradiniai duomenys bus aiškiai parodyti.','Upload a single-floor PDF or image. The planner crops the drawing, reads labels and draws recognized room outlines automatically. Missing input is shown clearly.');return oldT(k)};
 const stages=['PDF / vaizdas','Užrašai','Sienos','Mastelis','Patalpos','Trasos / sąmata'];
 function display(stage,message,result=null){area.replaceChildren();const title=document.createElement('h3');title.textContent=lt('Automatinis plano apdorojimas','Automatic plan processing','Automatisk planbehandling');area.append(title);const progress=document.createElement('div');progress.className='autoStages';stages.forEach((name,i)=>{const tag=document.createElement('span');tag.textContent=(i<stage?'✓ ':i===stage?'● ':'')+name;progress.append(tag)});area.append(progress);const p=document.createElement('p');p.textContent=message;area.append(p);if(running){const cancel=document.createElement('button');cancel.className='toolBtn';cancel.textContent=lt('Atšaukti apdorojimą','Cancel processing');cancel.onclick=window.cancelAutoPlan;area.append(cancel)}if(result){const summary=document.createElement('p');summary.textContent=lt(`Aptikta ${result.rooms.length} patalpų sričių. Brėžinio numerių: ${result.expected}. Trūksta: ${result.missing.join(', ')||'nėra'}.`,`Detected ${result.rooms.length} room regions; ${result.expected} drawing identifiers. Missing: ${result.missing.join(', ')||'none'}.`);area.append(summary);if(result.unknownUses.length){const missing=document.createElement('p');missing.className='autoIssue';missing.textContent=lt('Brėžinyje nėra patalpų paskirties legendos. Oro padavimo / ištraukimo ir rekuperatoriaus vietos neparenkame išgalvodami: '+result.unknownUses.join(', '),'Room uses are absent from the drawing. Air supply/extract and HRV placement require room-use evidence: '+result.unknownUses.join(', '));area.append(missing)}const button=document.createElement('button');button.className='toolBtn';button.textContent=lt('Peržiūrėti automatinio bandymo išvadą','View automatic run findings');button.onclick=()=>{panel='checks';render()};area.append(button)}}
 const rawRender=render;render=function(){rawRender();const f=state.floors.find(x=>x.id===state.selectedFloorId);if(!running&&f?.autoAnalysis)display(f.autoAnalysis.stage,f.autoAnalysis.message,f.autoAnalysis.result);else if(!running)area.replaceChildren()};
 window.cancelAutoPlan=()=>{sequence++;running=null;display(0,lt('Apdorojimas atšauktas. Originalus brėžinys išsaugotas.','Processing cancelled. Source drawing preserved.'))};
 window.runAutomaticPlan=async function(){const f=state.floors.find(x=>x.id===state.selectedFloorId);if(!f?.bg){openUpload();return}if(running){toast(lt('Planas jau apdorojamas','Plan is already processing'));return}if(state.rooms.some(r=>r.floorId===f.id)){panel='checks';render();return}const token=++sequence,initial=state,revision=f.sourceRevision,background=f.bg;running={token,floorId:f.id};const current=()=>sequence===token&&state===initial&&state.selectedFloorId===f.id&&f.sourceRevision===revision&&f.bg===background;
 try{display(1,lt('Skaitomi patalpų numeriai, plotai ir matmenys…','Reading room identifiers, areas and dimensions…'));const native=(f.textLabels||[]).filter(l=>l.source!=='local-ocr');let labels=native;const meaningful=native.filter(l=>A.roomCode(l.text)||/bedroom|living|kitchen|mieg|virtuv|von|svetain/i.test(l.text));if(meaningful.length<2){try{labels=[...native,...await VentPlanOcr.read(f.ocrImage||background,state.lang)]}catch(e){if(!current())return;f.autoOcrError=e.message;display(2,lt('Užrašų skaitymas nepavyko; tikrinamos sienos.','Label reading failed; checking walls.'))}}if(!current())return;const im=new Image();im.src=background;await im.decode();if(!current())return;const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=700;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);display(2,lt('Lyginamos sienų sritys su brėžinio numeriais…','Matching wall regions to drawing identifiers…'));await new Promise(resolve=>setTimeout(resolve,0));if(!current())return;const result=A.detect(ctx.getImageData(0,0,1000,700).data,labels);if(!current())return;display(3,lt('Tikrinami plotai ir nepriklausomi matmenys…','Checking areas and independent dimensions…'),result);if(!result.rooms.length){f.autoAnalysis={stage:2,message:lt('Patalpų ribų nepavyko nustatyti. Originalus planas nepakitęs.','Room outlines could not be resolved. Source preserved.'),result};render();return}
 pushHistory();f.textLabels=labels;f.ocrImage=null;f.automaticEvidence={version:A.VERSION,expected:result.expected,missing:result.missing,variants:result.variants,geometryComplete:result.geometryComplete,scale:result.scale};if(result.scale.line&&!result.scale.estimated){f.scale=result.scale.scale;f.calibrated=true;state.calibrationLines[f.id]={...result.scale.line,source:'automatic-width'};f.secondaryCalibration={...result.scale.secondaryLine,source:'automatic-width'}}else{f.calibrated=false;f.scaleEstimate=result.scale.scale;delete state.calibrationLines[f.id]}
 f.envelope=A.envelope(result.rooms);f.envelopeSource='room-union-provisional';const inserted=result.rooms.map(r=>({...r,id:'auto'+crypto.randomUUID().replaceAll('-',''),floorId:f.id,hpx:r.h,h:2.7,heightSource:'default-unconfirmed',name:(r.type==='other'?r.code:r.name)||r.code||lt('Patalpa','Room'),area:r.areaMismatch?0:r.areaM2??(f.calibrated?Number((G.area(r.polygon)*f.scale*f.scale).toFixed(2)):0),areaSource:r.areaMismatch?'unknown':r.areaM2!=null?'drawing':f.calibrated?'calibrated':'unknown',airflow:r.type==='other'?0:RULESET.airflowDefaults[r.type]||0,automatic:true}));state.rooms.push(...inserted);f.review=null;if(result.geometryComplete&&result.scale.line&&!result.scale.estimated&&!result.rooms.some(r=>r.areaMismatch))f.automaticGeometryReview={fingerprint:R.fingerprint(state,f.id),roomCount:inserted.length,method:'evidence-based-local',at:new Date().toISOString()};
 state.recognition={floorId:f.id,method:'automatic-local',reviewed:false,roomCount:inserted.length,uncertainties:[...(result.missing.length?['Missing room identifiers: '+result.missing.join(', ')]:[]),...(result.unknownUses.length?['Room uses missing from drawing']:[])]};if(!result.unknownUses.length){const services=inserted.filter(r=>['utility','technical'].includes(r.type));services.sort((a,b)=>inserted.reduce((n,r)=>n+Math.hypot(a.x+a.w/2-r.x-r.w/2,a.y+a.hpx/2-r.y-r.hpx/2),0)-inserted.reduce((n,r)=>n+Math.hypot(b.x+b.w/2-r.x-r.w/2,b.y+b.hpx/2-r.y-r.hpx/2),0));if(services[0]){const r=services[0],point=G.interiorPoint(r,{x:r.x+r.w/2,y:r.y+r.hpx/2},20);if(point)state.unit={...point,floorId:f.id,suggested:true}}}
 const readiness=A.autoReadiness(result),message=readiness.canDesign?lt('Patalpos ir matmenys paruošti. Nubraižytas preliminarus variantas; montavimui reikalinga specialisto patikra.','Rooms and dimensions prepared. Preliminary layout requires specialist approval.'):lt('Automatiškai nubraižytos atpažintos patalpų ribos. Ventiliacijos parinkimas sustabdytas, nes trūksta patikimų pradinių duomenų.','Recognized room outlines drawn automatically. Ventilation selection paused because reliable input is missing.');f.autoAnalysis={stage:readiness.canDesign?5:4,message,result:{rooms:result.rooms.map(r=>({code:r.code,name:r.name,type:r.type,areaM2:r.areaM2,areaMismatch:r.areaMismatch})),expected:result.expected,missing:result.missing,unknownUses:result.unknownUses,geometryComplete:result.geometryComplete,readiness,version:A.VERSION}};panel='checks';selected=null;saveSilent();render();
 }catch(e){console.error('VENT automatic plan',e);if(current()){f.autoAnalysis={stage:2,message:lt('Automatinis apdorojimas nepavyko. Brėžinys išsaugotas; galima pakartoti bandymą.','Automatic processing failed. Drawing preserved; retry is available.'),result:null};render()}}finally{if(running?.token===token){running=null;render()}}};
 const use=useFile;useFile=async function(){const previous=state.floors.find(x=>x.id===state.selectedFloorId)?.sourceRevision;if(running)window.cancelAutoPlan();await use();const f=state.floors.find(x=>x.id===state.selectedFloorId);if(f?.bg&&f.sourceRevision!==previous&&state.rooms.filter(r=>r.floorId===f.id).length===0)await window.runAutomaticPlan()};
 drawPlan=window.runAutomaticPlan;
 const audit=window.plannerReliability;window.plannerReliability=function(){const report=audit();for(const f of state.floors){if(f.automaticEvidence&&!f.review){report.issues.push({code:'automatic_drawing_review',severity:'warning',ref:f.id,detail:lt('Automatinė ribų patikra nepakeičia montavimo projekto patvirtinimo.','Automatic outline checks do not approve an installation design.')});report.warnings++}}return report};
}
