(function(root){
'use strict';const G=root.VentPlanGeometry,D=root.VentPlanRaster;
const VERSION='2026.10-auto-2';
function median(a){if(!a.length)return null;const b=a.slice().sort((x,y)=>x-y);return b[Math.floor(b.length/2)]}
function roomCode(text){const s=String(text||'').replace(/[–—−]/g,'-').replace(/\s/g,'').replace(/^-|-$|_/g,'');return /^\d{1,2}-\d{1,3}$/.test(s)?s:null}
function numeric(text){const s=String(text||'').trim().replace(/[,]/g,'.').replace(/["'²;:]$/g,'');if(!/^\d{1,4}(\.\d{1,2})?$/.test(s))return [];const n=Number(s);if(s.includes('.'))return n>.5&&n<500?[{value:n,repaired:false}]:[];return n>=100&&n<=49999?[{value:n/100,repaired:true}]:[]}
function anchors(labels){const combined=[...(labels||[])];for(const a of labels||[]){if(!/^\d{1,2}\s*[-–—]$/.test(String(a.text).trim()))continue;const b=(labels||[]).find(b=>/^\d{1,3}$/.test(String(b.text).trim())&&b.x>a.x&&b.x-a.x<Math.max(35,(a.width||20)*2)&&Math.abs(b.y-a.y)<8);if(b)combined.push({...a,text:a.text+b.text,x:(a.x+b.x)/2,width:(b.x+(b.width||0)/2)-(a.x-(a.width||0)/2),confidence:Math.min(a.confidence??100,b.confidence??100)})}const codes=[];for(const l of combined){if(!Number.isFinite(l.x)||!Number.isFinite(l.y)||l.confidence!==undefined&&l.confidence<35)continue;const code=roomCode(l.text);if(!code)continue;const prior=codes.find(x=>x.code===code&&Math.hypot(x.x-l.x,x.y-l.y)<20);if(prior){if((l.confidence||100)>(prior.confidence||100))Object.assign(prior,l,{code});continue}codes.push({...l,code})}return codes.sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true}))}
function legend(labels){const out=new Map();for(const l of labels||[]){if(l.confidence!==undefined&&l.confidence<55)continue;const m=String(l.text||'').match(/^\s*(\d{1,2}\s*[-–—]\s*\d{1,3})\s+(.+)$/);if(!m)continue;const code=roomCode(m[1]),classified=D.labelRoom({polygon:[{x:0,y:0},{x:1000,y:0},{x:1000,y:700},{x:0,y:700}]},[{text:m[2],x:100,y:100}]);if(!code||classified.type==='other')continue;const value={name:m[2].trim(),type:classified.type,source:'explicit-room-legend'};if(out.has(code)&&out.get(code)?.type!==value.type)out.set(code,null);else if(!out.has(code))out.set(code,value)}return out}
function annotate(room,labels){const inside=(labels||[]).filter(x=>Number.isFinite(x.x)&&Number.isFinite(x.y)&&G.contains(x,room.polygon));let r=D.labelRoom(room,inside);const ids=anchors(inside);r.codes=ids.map(x=>x.code);r.areaCandidates=[];if(ids.length===1){const a=ids[0];r.code=a.code;const entry=legend(labels).get(a.code);if(entry){r.type=entry.type;r.name=entry.name;r.useSource=entry.source}else r.name=r.type==='other'?a.code:r.name;r.labelAnchor={x:a.x,y:a.y};for(const l of inside){const dy=l.y-a.y,dx=Math.abs(l.x-a.x);if(dy<5||dy>Math.max(32,(a.height||10)*3.5)||dx>Math.max(22,(a.width||24)*.8)||l.confidence!==undefined&&l.confidence<35)continue;for(const n of numeric(l.text))r.areaCandidates.push({...n,text:l.text,confidence:l.confidence??100,distance:dy+dx,source:'paired-number'})}r.areaCandidates.sort((a,b)=>a.distance-b.distance||b.confidence-a.confidence);if(r.areaM2==null&&r.areaCandidates.length)r.areaM2=r.areaCandidates[0].value}r.exterior=inside.some(l=>/^(tr|terrace|terasa|balcony|balkon|balkong)$/i.test(l.text.trim()));return r}
function inferScale(rooms){const values=rooms.flatMap(r=>(r.areaCandidates||[]).map(a=>({scale:Math.sqrt(a.value/G.area(r.polygon)),room:r,area:a}))).filter(x=>Number.isFinite(x.scale)&&x.scale>.001&&x.scale<.2);let best=[];for(const candidate of values){const group=values.filter(x=>Math.abs(x.scale/candidate.scale-1)<.055);const unique=new Map();for(const x of group)if(!unique.has(x.room.code)||x.area.confidence>unique.get(x.room.code).area.confidence)unique.set(x.room.code,x);if(unique.size>best.length)best=[...unique.values()]}
 if(best.length<4)return {scale:null,evidence:[],reason:'scale_insufficient'};const scale=median(best.map(x=>x.scale)),spread=Math.max(...best.map(x=>Math.abs(x.scale/scale-1)));if(spread>.055)return {scale:null,evidence:[],reason:'scale_disagreement'};return {scale,evidence:best.map(x=>({code:x.room.code,area:x.area.value,repaired:x.area.repaired,confidence:x.area.confidence})),spread,source:'printed-area-consensus',estimated:true}}
function inferDimensions(rooms,labels,areaScale){if(!areaScale)return {primary:null,secondary:null,evidence:[]};const evidence=[];for(const r of rooms){const b=G.boundsOf(r.polygon);if(Math.abs(G.area(r.polygon)-b.w*b.h)>.04*b.w*b.h)continue;for(const l of labels||[]){if(!G.contains(l,r.polygon)||l.confidence!==undefined&&l.confidence<55)continue;const number=numeric(l.text).find(n=>!n.repaired&&n.value>=1&&n.value<=20);if(!number)continue;const atBottom=Math.abs(l.y-(b.y+b.h))<25,atTop=Math.abs(l.y-b.y)<25,centered=Math.abs(l.x-(b.x+b.w/2))<b.w*.25;if(!centered||!atBottom&&!atTop)continue;const scale=number.value/b.w;if(Math.abs(scale/areaScale-1)>.04)continue;evidence.push({code:r.code,scale,line:{x1:b.x,y1:atBottom?b.y+b.h:b.y,x2:b.x+b.w,y2:atBottom?b.y+b.h:b.y,meters:number.value},source:'room-width-label',confidence:l.confidence??100})}}evidence.sort((a,b)=>b.line.meters-a.line.meters||b.confidence-a.confidence);const primary=evidence[0]||null,secondary=primary?evidence.find(e=>e.code!==primary.code&&Math.abs(e.scale/primary.scale-1)<.035)||null:null;return {primary,secondary,evidence}}
function select(variants,labels){const ids=anchors(labels),ranked=variants.map(v=>{const rooms=v.rooms.map(r=>annotate(r,labels));const accepted=rooms.filter(r=>!r.exterior&&(!ids.length||r.codes.length===1));const distinct=new Set(accepted.flatMap(r=>r.codes));const merged=rooms.filter(r=>r.codes.length>1).length;return {...v,rooms:accepted,allRooms:rooms,score:distinct.size*100-merged*80-accepted.filter(r=>!r.codes.length).length*10,coverage:distinct.size,merged}}).sort((a,b)=>b.score-a.score||a.gap-b.gap);const best=ranked[0]||{rooms:[],gap:0};const typical=median(best.rooms.map(r=>G.area(r.polygon)))||0;const unassigned=(best.allRooms||[]).filter(r=>!r.exterior&&!r.codes.length&&G.area(r.polygon)>Math.max(1200,typical*.4));if(ids.length)best.rooms.push(...unassigned);const used=new Set(best.rooms.flatMap(r=>r.codes));const duplicates=best.rooms.some((r,i)=>best.rooms.some((s,j)=>j<i&&r.code&&r.code===s.code));const missing=ids.filter(x=>!used.has(x.code)).map(x=>x.code);const overlap=best.rooms.some((r,i)=>best.rooms.some((s,j)=>j<i&&G.overlapArea(r.polygon,s.polygon)>100));const scale=inferScale(best.rooms);const dimensions=inferDimensions(best.rooms,labels,scale.scale);if(dimensions.primary&&dimensions.secondary){scale.areaScale=scale.scale;scale.scale=dimensions.primary.scale;scale.estimated=false;scale.source='two-width-labels';scale.line=dimensions.primary.line;scale.secondaryLine=dimensions.secondary.line}for(const r of best.rooms){if(scale.scale){const measured=G.area(r.polygon)*scale.scale**2,candidates=r.areaCandidates||[];const match=candidates.find(a=>Math.abs(a.value/measured-1)<.15);r.areaM2=match?.value??r.areaM2;r.areaMismatch=r.areaM2!=null&&Math.abs(r.areaM2/measured-1)>.15;r.areaRepaired=!!match?.repaired}r.geometryReviewed=false;r.labelReviewed=false}
 return {...best,version:VERSION,expected:ids.length,unassigned:unassigned.length,missing,duplicates,overlap,scale,dimensions,geometryComplete:ids.length>0&&!unassigned.length&&!missing.length&&!duplicates&&!overlap&&best.rooms.length===ids.length,unknownUses:best.rooms.filter(r=>r.type==='other').map(r=>r.code||r.name),variants:ranked.map(x=>({gap:x.gap,coverage:x.coverage,merged:x.merged,score:x.score}))}}
function detect(pixels,labels=[]){const variants=[16,24,28,32,40,48].map(gap=>({...D.detect(pixels,1000,700,{gap,thinWalls:true,lineLength:16,minimumArea:600}),gap}));return select(variants,labels)}
function cropBounds(pixels,width,height){if(width<40||height<40||width*height>5e6||pixels.length!==width*height*4)return null;const ink=new Uint8Array(width*height);for(let i=0;i<ink.length;i++){const k=i*4,a=pixels[k+3]/255;ink[i]=((pixels[k]+pixels[k+1]+pixels[k+2])/3*a+255*(1-a))<170?1:0}const mask=new Uint8Array(ink.length),min=Math.max(12,Math.round(Math.min(width,height)*.035));for(let y=0;y<height;y++){let start=-1;for(let x=0;x<=width;x++)if(x<width&&ink[y*width+x]){if(start<0)start=x}else if(start>=0){if(x-start>=min)for(let xx=start;xx<x;xx++)mask[y*width+xx]=1;start=-1}}for(let x=0;x<width;x++){let start=-1;for(let y=0;y<=height;y++)if(y<height&&ink[y*width+x]){if(start<0)start=y}else if(start>=0){if(y-start>=min)for(let yy=start;yy<y;yy++)mask[yy*width+x]=1;start=-1}}
 const seen=new Uint8Array(mask.length),q=new Int32Array(mask.length);let best=null;for(let k=0;k<mask.length;k++){if(!mask[k]||seen[k])continue;let head=0,tail=1,minX=width,minY=height,maxX=0,maxY=0;q[0]=k;seen[k]=1;while(head<tail){const p=q[head++],x=p%width,y=Math.floor(p/width);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const xx=x+dx,yy=y+dy,n=yy*width+xx;if(xx>=0&&yy>=0&&xx<width&&yy<height&&mask[n]&&!seen[n]){seen[n]=1;q[tail++]=n}}}const w=maxX-minX,h=maxY-minY,score=w*h;if(w>width*.15&&h>height*.15&&tail>min*4&&(!best||score>best.score))best={x:minX,y:minY,w:w+1,h:h+1,score}}
 if(!best)return null;const pad=Math.max(8,Math.round(Math.max(best.w,best.h)*.045));const x=Math.max(0,best.x-pad),y=Math.max(0,best.y-pad),w=Math.min(width,best.x+best.w+pad)-x,h=Math.min(height,best.y+best.h+pad)-y;if(w*h>width*height*.94)return null;return {x:x/width,y:y/height,w:w/width,h:h/height,source:'structural-lines'} }
function envelope(rooms){if(!rooms.length)return null;const w=500,h=350,mask=new Uint8Array(w*h);for(const r of rooms){const poly=r.polygon;for(let y=0;y<h;y++){const yy=y*2+1,cross=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];if((a.y>yy)!==(b.y>yy))cross.push(a.x+(yy-a.y)*(b.x-a.x)/(b.y-a.y))}cross.sort((a,b)=>a-b);for(let i=0;i+1<cross.length;i+=2)for(let x=Math.max(0,Math.floor(cross[i]/2));x<Math.min(w,Math.ceil(cross[i+1]/2));x++)mask[y*w+x]=1}}let joined=D.closeAxis(D.closeAxis(mask,w,h,12,false),w,h,12,true);const expanded=joined.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++)if(joined[y*w+x])for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)expanded[(y+dy)*w+x+dx]=1;const regions=D.components(expanded,w,h,1);const largest=regions.regions.sort((a,b)=>b.count-a.count)[0];if(!largest)return null;const polygon=D.simplify(D.contour(regions.labels,w,h,largest,2),2);return G.validPolygon(polygon)&&rooms.every(r=>r.polygon.every(p=>G.contains(p,polygon)))?polygon:null}
function autoReadiness(result){const reasons=[];if(!result.geometryComplete)reasons.push('incomplete_geometry');if(result.unknownUses?.length)reasons.push('missing_room_uses');if(!result.scale?.scale)reasons.push('missing_scale');if(result.scale?.estimated)reasons.push('estimated_scale');if(result.rooms?.some(r=>r.areaMismatch))reasons.push('area_mismatch');return {canDraw:result.geometryComplete,canDesign:reasons.length===0,reasons}}
// Explicit user input completes missing semantics without changing detected geometry.
function prepareInputs(rooms,choices,unitId,defaults){
 const errors=[],ids=new Set(rooms.map(r=>r.id));
 if(!rooms.length)errors.push('rooms_missing');
 if(!ids.has(unitId))errors.push('unit_room_missing');
 const next=rooms.map(r=>{const type=choices[r.id];if(!Object.hasOwn(defaults,type)||type==='other'){errors.push('room_use:'+r.id);return {...r}}return {...r,type,airflow:defaults[type],supplyAirflow:type==='livingKitchen'?defaults[type]:undefined,extractAirflow:type==='livingKitchen'?45:undefined,useSource:'user-confirmed'}});
 const direction=type=>type==='livingKitchen'?'mixed':['living','bedroom','office'].includes(type)?'supply':['kitchen','bathroom','wc','utility','technical'].includes(type)?'extract':'transit';
 const sum=kind=>next.reduce((n,r)=>n+(direction(r.type)==='mixed'?r[kind+'Airflow']:direction(r.type)===kind?r.airflow:0),0);
 let supply=sum('supply'),extract=sum('extract');
 if(!supply||!extract)errors.push('air_directions_missing');
 if(errors.length)return {errors};
 const lower=supply<extract?'supply':'extract',factor=Math.max(supply,extract)/Math.min(supply,extract);
 for(const r of next){const d=direction(r.type),key=d==='mixed'?lower+'Airflow':'airflow';if(d===lower||d==='mixed')r[key]=Number((r[key]*factor).toFixed(2));if(r.airflow>300||r.supplyAirflow>300||r.extractAirflow>300)errors.push('flow_limit:'+r.id)}
 const adjustable=next.filter(r=>direction(r.type)===lower||direction(r.type)==='mixed').at(-1),key=direction(adjustable.type)==='mixed'?lower+'Airflow':'airflow';adjustable[key]=Number((adjustable[key]+Math.max(supply,extract)-sum(lower)).toFixed(2));
 const unitRoom=next.find(r=>r.id===unitId),point=G.interiorPoint(unitRoom,{x:unitRoom.x+unitRoom.w/2,y:unitRoom.y+unitRoom.hpx/2},20);
 if(!point||!G.contains(point,G.outline(unitRoom)))errors.push('unit_room_invalid');
 return {errors,rooms:next,unit:point?{...point,floorId:unitRoom.floorId,roomId:unitId,source:'user-room-selection'}:null,supply:sum('supply'),extract:sum('extract')};
}
root.VentPlanAuto={VERSION,median,roomCode,numeric,anchors,legend,annotate,inferScale,inferDimensions,select,detect,cropBounds,envelope,autoReadiness,prepareInputs};
})(typeof window==='undefined'?globalThis:window);
