(()=>{
 'use strict';
 const {E,s,pages,link,button,field,form,submit,notice,panel,heading,date,toast,api,go,modal}=App;
 const kinds={invite:'Kvietimo prašymas',help:'Pagalba',privacy:'Privatumo klausimas',report:'Pranešimas apie pažeidimą'};
 const refresh=async()=>{await App.render(false);};
 function codeCard(code){return panel(E('h2',{},'Išsaugok privatų atsakymo kodą.'),E('p',{},'Atsakymą peržiūrėsi skiltyje „Mano užklausos būsena“. Kodas suteikia prieigą prie šios užklausos ir jos atsakymo — nesidalink juo.'),E('code',{class:'secure-code'},code),E('div',{class:'actions'},button('Išsaugoti kodą faile',()=>App.download('telkinys-uzklausos-kodas.txt','Telkinys — privatus užklausos kodas\n'+code+'\nPeržiūra: https://telkinys.lt/?view=access&mode=status\nKodas galioja 30 dienų. Nesiųsk jo viešai. El. laiškų sistema nesiunčia.\n')),button('Peržiūrėti būseną',()=>go({view:'access',mode:'status'}),'btn primary')));}
 pages.access=async p=>{
  const status=p.mode==='status',kind=Object.hasOwn(kinds,p.kind)?p.kind:'invite';
  const root=E('div',{class:'narrow stack'},heading(status?'Mano užklausos būsena':kind==='invite'?'Prisijunk prie pirmųjų dalyvių.':'Pagalba be prisijungimo',status?'Privatus atsakymas pasiekiamas tik su tavo kodu.':'Jokios paskyros ar el. pašto šiai užklausai nereikia.'),E('nav',{class:'tabs','aria-label':'Pagalbos veiksmai'},link('Prašyti kvietimo',{view:'access',kind:'invite'},!status&&kind==='invite'?'active':''),link('Gauti pagalbą',{view:'access',kind:'help'},!status&&kind!=='invite'?'active':''),link('Mano užklausos būsena',{view:'access',mode:'status'},status?'active':'')));
  if(status){const target=E('section',{class:'stack','aria-live':'polite'});root.append(panel(form([field('accessCode','Privatus atsakymo kodas','password',s.publicCaseCode||'',{required:true,minLength:43,maxLength:43,autocomplete:'off',autocapitalize:'none',spellcheck:'false'}),submit('Peržiūrėti atsakymą')],async fd=>{
    const code=String(fd.get('accessCode')).trim();const data=await api('public-status',{accessCode:code}),r=data.request;s.publicCaseCode=code;
    target.replaceChildren(panel(E('div',{class:'row between'},E('h2',{},kinds[r.kind]),E('span',{class:'badge'},r.resolved?'Atsakyta':'Laukiama peržiūros')),E('p',{class:'hint'},'Pateikta '+date(r.created_at)+' · Nr. '+r.id.slice(0,8)),E('p',{class:'text-wrap'},r.body),E('h3',{},'Atsakymas'),E('p',{class:'text-wrap'},r.reply||'Atsakymo dar nėra. Grįžk į šią skiltį vėliau. El. laiškai nesiunčiami.'),E('p',{class:'hint'},'Prieigos kodas galioja iki '+date(r.expires_at)),button('Pašalinti mano užklausą ir atsakymą',async()=>{if(!confirm('Pašalinti šią užklausą? Atsakymas ir kvietimas, jei jis pateiktas atsakyme, šiame puslapyje nebebus pasiekiami.'))return;await api('public-delete',{accessCode:code});delete s.publicCaseCode;target.replaceChildren(notice('Užklausa pašalinta.'));},'btn danger')));
   })),target);return root;}
  root.append(notice('Nerašyk slaptažodžių, bankinių duomenų, dokumentų numerių ar jautrios informacijos. Atsakymą tikrinsi pats, naudodamas vieną kartą parodytą privatų kodą. El. laiškų nesiunčiame.'));
  if(!s.config?.operator)root.append(E('p',{class:'hint'},'Operatoriaus rekvizitai dar nepateikti. Tai uždara bandomoji aplinka, ne neatidėliotinos pagalbos kanalas. Rekvizitų būseną rasi privatumo puslapyje.'));
  const f=form([field('kind','Kreipimosi tema',Object.entries(kinds),kind),E('div',{class:'form-grid'},field('interest','Kaip planuoji naudotis?',[['buyer','Ieškau pasiūlymų'],['provider','Siūlau paslaugas ar prekes'],['other','Kita']],'buyer'),field('city','Miestas (nebūtina)','text','',{maxLength:60,placeholder:'Pvz., Kaunas'})),field('body','Trumpai aprašyk','textarea',p.q||'',{required:true,minLength:10,maxLength:2000,rows:5,placeholder:kind==='invite'?'Kokios paslaugos ar pasiūlymo ieškai? Ką norėtum pasiūlyti?':'Kas neveikia arba kokio atsakymo reikia?'}),E('div',{class:'v15-honeypot','aria-hidden':'true'},field('website','Palik tuščią','text','',{tabindex:-1,autocomplete:'off',maxLength:100})),E('label',{class:'checkline'},E('input',{type:'checkbox',name:'consent',required:true}),E('span',{},'Susipažinau su ',link('privatumo informacija',{view:'privacy'}),'. Suprantu, kad užklausa bus perduota projekto administratoriui, o atsakymą turėsiu patikrinti su privačiu kodu.')),submit(kind==='invite'?'Pateikti kvietimo prašymą':'Pateikti užklausą')],async(fd,_intent,f)=>{
   const data=await api('public-request',{request:{kind:fd.get('kind'),interest:fd.get('interest'),city:fd.get('city'),body:fd.get('body'),website:fd.get('website'),consent:fd.has('consent')}});s.publicCaseCode=data.accessCode;f.replaceWith(codeCard(data.accessCode));toast('Užklausa gauta. Išsaugok privatų kodą.');
  });f.classList.add('panel','stack');root.append(f,E('p',{class:'hint'},'Kvietimo prašymas nėra automatinė registracija. Dalyvius patvirtina administratorius. Atsakymo laikas dar negarantuojamas.'));return root;
 };
 const oldLogin=pages.login;
 pages.login=async p=>{const node=await oldLogin(p);if(!s.user)node.append(E('div',{class:'v15-auth-help'},link('Neturi kvietimo? Pateik prašymą',{view:'access',kind:'invite'},'btn wide'),link('Nepavyksta prisijungti ar atkurti paskyros?',{view:'access',kind:'help'},'btn quiet wide')));return node;};
 const oldAccount=pages.account;
 pages.account=async p=>{const node=await oldAccount(p);if(s.user){const shortcuts=E('nav',{class:'v15-account-links','aria-label':'Poreikiai ir specialistų veikla'},link('Mano poreikiai ir susitarimai',{view:'needs'},'btn primary'),link('Specialisto užklausos',{view:'needs',tab:'provider'},'btn'));node.insertBefore(shortcuts,node.children[1]||null);}return node;};
 pages.help=async()=>E('div',{class:'narrow stack'},heading('Pagalba, kurią pasieksi ir neprisijungęs.'),panel(E('h2',{},'Negali patekti į paskyrą?'),E('p',{},'Automatinį atkūrimą gali atlikti turėdamas registracijos metu išsaugotą atkūrimo kodą. Jei jo neturi, pateik pagalbos užklausą. Prieiga neatkuriama vien pagal nepatvirtintą pareiškimą.'),E('div',{class:'actions'},link('Atkurti su kodu',{view:'login',mode:'recover'},'btn'),link('Parašyti pagalbai',{view:'access',kind:'help'},'btn primary'))),panel(E('h2',{},'Kvietimai ir atsakymai'),E('p',{},'Kvietimo gali paprašyti be paskyros. Išsaugok gautą privatų kodą ir su juo patikrink atsakymą. Automatinio el. pašto dar nėra.'),E('div',{class:'actions'},link('Prašyti kvietimo',{view:'access',kind:'invite'},'btn'),link('Tikrinti mano užklausą',{view:'access',mode:'status'},'btn'))),panel(E('h2',{},'Pažeidimas arba privatumo klausimas'),E('p',{},'Nurodyk pasiūlymo ar poreikio numerį ir konkrečią problemą. Neviesink kitų žmonių dokumentų, kontaktų ar prisijungimo kodų.'),E('div',{class:'actions'},link('Pranešti apie pažeidimą',{view:'access',kind:'report'},'btn'),link('Privatumo užklausa',{view:'access',kind:'privacy'},'btn'))),link('Operatorius ir duomenų tvarkymas',{view:'privacy'},'btn quiet'));
 pages.about=async()=>E('div',{class:'narrow stack'},heading('Nuo poreikio iki aiškaus susitarimo.'),panel(E('h2',{},'Rask arba aprašyk, ko reikia.'),E('p',{},'Skelbimų paieškoje gali ieškoti daiktų, būsto, automobilio, darbo ar paslaugos. Pervežimui, valymui ir baldų surinkimui jau galima sukurti struktūruotą poreikį.'),link('Aprašyti poreikį',{view:'need-new'},'btn primary')),panel(E('h2',{},'Palygink sąlygas, ne vien skaičių.'),E('p',{},'Specialistas nurodo galutinę sumą, įskaičiuotus darbus, išimtis, siūlomą laiką ir pasiūlymo galiojimą. Iki penkių galiojančių pasiūlymų vienam poreikiui. Kitų specialistų kainos jų konkurentams nerodomos.')),panel(E('h2',{},'Abi pusės patvirtina.'),E('p',{},'Pasirinkus pasiūlymą sąlygos užfiksuojamos susitarimo kortelėje. Ją patvirtina ir specialistas. Žinutės bei sąlygų kopija lieka dalyvių paskyrose. Kortelė nėra Telkinio mokėjimo ar paslaugos kokybės garantija.')),panel(E('h2',{},'Kas dar kuriama?'),E('p',{},'Mokėjimai, tapatybės ir kvalifikacijos patikros, AI modelis, kainų agregavimas, automatiniai el. laiškai ir visų kategorijų projektai nėra įjungti. Tai uždara beta: specialistų pasiūlos ir atsakymo termino negarantuojame.')),E('div',{class:'actions'},link('Prašyti kvietimo',{view:'access',kind:'invite'},'btn primary'),link('Pagalba',{view:'help'},'btn')));
 for(const view of ['privacy','terms']){const previous=pages[view];pages[view]=async p=>{const root=await previous(p);root.append(E('section',{class:'v15-policy-addendum'},E('h2',{},'V15 papildymas: poreikiai ir vieša pagalba'),E('p',{},'Poreikio juodraštį mato jo autorius. Patvirtintą poreikį gali skaityti prisijungę specialistai, pasirinkę atitinkamą paslaugą ir miestą. Pasiūlymo kainą, privatų aptarimą ir susitarimo kortelę mato poreikio autorius bei konkretus specialistas. Administratoriai peržiūri pateiktus poreikius.'),E('p',{},'Pagalbai be prisijungimo saugoma kreipimosi tema, pasirinktas miestas ir aprašymas. El. pašto ar telefono nereikalaujama. Vieną kartą parodytas privatus kodas suteikia prieigą prie užklausos, atsakymo ir pašalinimo. Kodas galioja 30 dienų. Pasibaigusių įrašų valymas vykdomas administratoriaus priežiūros veiksmu; tai nėra pažadas apie jau įjungtą automatinį valymą.'),E('p',{},'Poreikių duomenys įtraukti į paskyros eksportą. Šių duomenų kopiją taip pat gali parsisiųsti poreikių skiltyje. Paskyros pašalinimas paveikia ir susijusių poreikių, pasiūlymų bei susitarimų prieinamumą; prieš šalindamas pasiimk svarbių susitarimų kopijas.'),E('p',{},'Specialisto teritorija ir užklausų priėmimas yra paties specialisto nurodyti duomenys, ne nepriklausoma patikra. Pasirinkimas ir abiejų pusių pažymėtas užbaigimas nėra patvirtinto mokėjimo įrodymas.'),link('Kreiptis be prisijungimo',{view:'access',kind:'privacy'},'btn')));return root;};}
 const oldAdmin=App.adminPane;
 App.adminPane=async()=>{
  const root=await oldAdmin(),[inbox,moderation]=await Promise.all([api('access-inbox'),api('needs-moderation')]);
  const queue=panel(E('h2',{},'Nauji poreikiai ('+moderation.needs.length+')'));
  for(const n of moderation.needs)queue.append(E('article',{class:'admin-row'},E('h3',{},n.title),E('p',{class:'hint'},n.city+' · '+n.service+' · '+n.display_name),E('p',{class:'text-wrap'},n.scope),E('p',{},n.timing),button('Peržiūrėti poreikį',()=>modal('Poreikio peržiūra',E('p',{class:'text-wrap'},n.scope),form([field('note','Paaiškinimas (būtinas grąžinant taisyti)','textarea','',{maxLength:800}),E('div',{class:'actions'},submit('Patvirtinti specialistams','open'),submit('Grąžinti taisyti','rejected',false))],async(fd,state)=>{await api('need-moderate',{id:n.id,version:n.version,state,note:fd.get('note')});App.$('#dialog').close();await refresh();})),'btn small primary')));
  if(!moderation.needs.length)queue.append(E('p',{class:'muted'},'Poreikių peržiūros eilė tuščia.'));root.prepend(queue);
  const cases=panel(E('h2',{},'Kvietimai ir pagalba be prisijungimo'),E('p',{class:'hint'},'Atsakymą lankytojas peržiūrės su savo privačiu kodu. El. laiškai nesiunčiami. Kvietimo kodą kurk tik nustatęs operatoriaus rekvizitus ir patvirtinęs dokumentus.'));
  for(const r of inbox.requests)cases.append(E('article',{class:'admin-row'},E('div',{class:'row between'},E('strong',{},kinds[r.kind]+' · '+(r.city||'Miestas nenurodytas')),E('span',{class:'badge'},r.resolved?'Atsakyta':'Laukia')),E('p',{class:'text-wrap'},r.body),r.reply?E('p',{class:'text-wrap'},'Atsakymas: '+r.reply):null,button('Atsakyti privačiai',()=>modal('Atsakymas į užklausą',E('p',{class:'text-wrap'},r.body),form([field('reply','Atsakymas','textarea',r.reply||'',{required:true,minLength:10,maxLength:3000}),submit('Išsaugoti atsakymą')],async fd=>{await api('access-reply',{id:r.id,reply:fd.get('reply')});App.$('#dialog').close();await refresh();})),'btn small')));
  if(!inbox.requests.length)cases.append(E('p',{class:'muted'},'Užklausų dar nėra.'));root.append(cases);
  if(s.user.role==='admin'){
   const metrics=await api('needs-metrics');root.prepend(E('section',{class:'panel'},E('h2',{},'Poreikių bandymo rodikliai'),E('div',{class:'metric-grid'},[['needs','Poreikiai'],['with_offer','Su pasiūlymu'],['confirmed','Patvirtinti susitarimai'],['completed','Abipusiai užbaigti'],['providers','Priimantys specialistai']].map(([key,label])=>E('div',{class:'metric'},E('strong',{},metrics.counts[key]),E('span',{},label)))));
   root.append(panel(E('h2',{},'Rankinė priežiūra'),E('p',{class:'muted'},'Šie veiksmai nėra automatinis grafikas ir nepakeičia atsarginių kopijų. Šalinami tik anksčiau pažymėti, išlaukti pašalintų failų darbai arba pasibaigusios viešos pagalbos užklausos.'),E('div',{class:'actions'},button('Vykdyti numatytą failų valymą',async()=>{const result=await api('media-maintenance');toast('Pašalinta failų: '+result.removed);}),button('Pašalinti pasibaigusias pagalbos užklausas',async()=>{if(!confirm('Pašalinti užklausas, kurių 30 dienų prieigos galiojimas jau pasibaigęs?'))return;const result=await api('access-prune');toast('Pašalinta užklausų: '+result.removed);await refresh();}))));
  }
  return root;
 };
})();