(()=>{
 'use strict';
 const {E,s,pages,link,button,field,form,submit,notice,panel,empty,heading,money,toast,api,get,go}=App;
 const categories=[['services','Paslaugos'],['items','Daiktai ir prekės'],['home','Būstas'],['auto','Auto'],['jobs','Darbai']];
 const activeSearch=p=>['q','category','city','min','max','unit'].some(k=>p[k]);
 pages.home=async p=>{
  s.lastSearch={...p};const searched=activeSearch(p),root=E('div',{class:'v15-market'});
  if(!searched)root.append(E('section',{class:'v15-hero'},E('p',{class:'kicker'},'NUO POREIKIO IKI SUSITARIMO'),E('h1',{},'Neieškok portalo.',E('br'),'Pasakyk, ko reikia.'),E('p',{class:'lead'},'Rask pasiūlymą arba aprašyk darbą. Palygink sąlygas ir išsaugok susitarimą vienoje vietoje.')));
  else root.append(E('div',{class:'v15-search-heading'},E('h1',{},'Tavo paieška'),link('Pradžia',{},'btn quiet small')));
  const intent=E('nav',{class:'v15-intent','aria-label':'Ką norėtum padaryti?'},E('span',{'aria-current':'page'},'Ieškau pasiūlymo'),link('Noriu gauti pasiūlymų',{view:'need-new',q:p.q||'',city:p.city||''}),link('Turiu ką pasiūlyti',{view:'edit'}));
  const more=E('details',{class:'v15-filters',open:!!(p.category||p.min||p.max||p.unit||p.sort&&p.sort!=='newest')},E('summary',{},'Kategorija ir papildomi filtrai'),E('div',{class:'form-grid'},field('category','Kategorija',[['','Visos kategorijos'],...categories],p.category||''),field('unit','Kokias kainas lyginti?',[['','Pagal paiešką'],['total','Visa suma, €'],['hour','Valandinis įkainis, €/val.'],['month','Mėnesio suma, €/mėn.'],['from','Pradinė kaina „nuo“'],['negotiable','Sutartinė kaina']],p.unit||''),field('min','Kaina nuo','number',p.min||'',{min:0,max:1e9,step:'0.01',inputmode:'decimal'}),field('max','Kaina iki','number',p.max||'',{min:0,max:1e9,step:'0.01',inputmode:'decimal'}),field('sort','Rezultatų tvarka',[['newest','Naujausi'],['price-asc','Pigiausi pirmi'],['price-desc','Brangiausi pirmi']],p.sort||'newest')),E('p',{class:'hint'},'Valandinį įkainį lygink su valandiniu, visą darbų sumą — su visa suma. Filtrai pritaikomi paspaudus „Rasti“.'));
  const f=form([E('div',{class:'v15-search-fields'},field('q','Ko ieškai?','search',p.q||'',{maxLength:300,placeholder:'Pvz., iPhone 15 Pro 256 GB iki 700 €',autocomplete:'off',enterkeyhint:'search'}),field('city','Kur?','text',p.city||'',{maxLength:60,placeholder:'Visa Lietuva'}),submit('Rasti')),more],async fd=>{
   const values=Object.fromEntries(fd);if(values.min!==''&&values.max!==''&&Number(values.min)>Number(values.max))throw new Error('Kaina „nuo“ negali būti didesnė už kainą „iki“.');
   go(Object.fromEntries(Object.entries(values).filter(([,v])=>v!=='')));
  });f.classList.add('v15-search-panel');
  root.append(intent,f,E('nav',{class:'categories','aria-label':'Pasiūlymų kategorijos'},link('Visi',{},'chip '+(!p.category?'active':'')),categories.map(([key,label])=>link(label,{category:key},'chip '+(p.category===key?'active':'')))));
  if(!searched)root.append(E('section',{class:'v15-service-strip','aria-label':'Gauk pasiūlymų savo darbui'},E('div',{},E('strong',{},'Ne skelbimo, o pagalbos?'),E('p',{},'Pradėk nuo konkretaus darbo.')),E('div',{class:'actions'},link('Pervežimas',{view:'need-new',service:'moving'},'btn'),link('Valymas',{view:'need-new',service:'cleaning'},'btn'),link('Baldų surinkimas',{view:'need-new',service:'assembly'},'btn'))));
  let data;try{data=await get({...p,op:'search'});}catch(error){root.append(notice(error.message,'error'),button('Bandyti dar kartą',()=>App.render(false)));return root;}
  const ip=data.interpreted||{};
  const criteria=[ip.category?App.categories[ip.category]:null,ip.city,ip.district,ip.rooms?ip.rooms+' kamb.':null,ip.min!==null&&ip.min!==undefined?'nuo '+money(ip.min/100,ip.unit||'total'):null,ip.max!==null&&ip.max!==undefined?'iki '+money(ip.max/100,ip.unit||'total'):null,ip.brand?ip.brand.toUpperCase():null,ip.year?'nuo '+ip.year+' m.':null,ip.mileage?'iki '+ip.mileage+' km':null,ip.excludeFirst?'Ne pirmas aukštas':null].filter(Boolean);
  if(searched&&criteria.length)root.append(E('div',{class:'v15-criteria'},E('span',{class:'hint'},'Taikomi kriterijai:'),criteria.map(v=>E('span',{class:'badge'},v)),button('Patikslinti',()=>{more.open=true;f.querySelector('[name=category]').focus();},'btn quiet small')));
  for(const warning of ip.warnings||[])root.append(notice(warning,'warning'));
  const save=button('Išsaugoti paiešką',async()=>{if(!s.user){s.afterAuth={...p};go({view:'login'});return;}const filters=Object.fromEntries(Object.entries(p).filter(([k])=>['q','category','city','min','max','sort','unit'].includes(k)));await api('save-search',{name:(p.q||categories.find(x=>x[0]===p.category)?.[1]||'Visi pasiūlymai').slice(0,120),filters});await App.refreshMe();toast('Paieška išsaugota. Automatinių el. laiškų dar nesiunčiame.');},'btn small',{disabled:!searched});
  root.append(E('div',{class:'section-head'},E('div',{},E('h2',{},searched?'Paieškos rezultatai':'Pasiūlymai Telkinyje'),E('p',{class:'muted small-text'},'Rasta: '+data.total)),E('div',{class:'actions'},save,s.compare.size?link('Palyginti ('+s.compare.size+')',{view:'compare'},'btn primary small'):null)));
  if(data.items.length)root.append(E('div',{class:'grid'},data.items.map(App.card)));
  else root.append(E('section',{class:'v15-empty'},E('div',{},E('p',{class:'kicker'},searched?'PAIEŠKĄ GALIMA TĘSTI KITAIP':'KURIAME SU PIRMAISIAIS DALYVIAIS'),E('h3',{},searched?'Tikslių atitikmenų dar nėra.':'Čia vieta tikriems pasiūlymams.'),E('p',{},searched?'Netinkančių skelbimų vietoje tikslių rezultatų nerodome. Patikslink kriterijus arba aprašyk paslaugos poreikį.':'Katalogą pildo beta dalyviai. Demonstracinių skelbimų nėra, o specialisto atsakymas nėra garantuojamas.')),E('div',{class:'v15-empty-actions'},link('Aprašyti paslaugos poreikį',{view:'need-new',q:p.q||'',city:p.city||''},'btn primary'),s.user?link('Įkelti pasiūlymą',{view:'edit'},'btn'):link('Prašyti kvietimo',{view:'access',kind:'invite'},'btn'),searched?link('Išvalyti paiešką',{},'btn quiet'):null)));
  if(data.pages>1)root.append(E('nav',{class:'pagination','aria-label':'Rezultatų puslapiai'},data.page>1?link('← Ankstesnis',{...p,page:data.page-1},'btn'):null,E('span',{},data.page+' / '+data.pages),data.page<data.pages?link('Kitas →',{...p,page:data.page+1},'btn'):null));
  if(!searched)root.append(E('section',{class:'v15-how'},E('div',{class:'section-head'},E('h2',{},'Mažiau žinučių. Aiškesnės sąlygos.'),link('Kaip tai veikia',{view:'about'},'btn quiet')),E('div',{class:'v15-steps'},[['01','Aprašyk poreikį','Kas, kur ir kada reikalinga. Kontaktų viešinti nereikia.'],['02','Palygink atsakymus','Visa suma, įskaičiuoti darbai, išimtys ir siūlomas laikas.'],['03','Patvirtink susitarimą','Pasirinkimą patvirtina ir specialistas. Sąlygų kopija lieka tavo paskyroje.']].map(([n,h,t])=>E('article',{},E('span',{class:'step-number'},n),E('h3',{},h),E('p',{},t))))),E('section',{class:'v15-professional'},E('div',{},E('p',{class:'kicker'},'SPECIALISTAMS'),E('h2',{},'Rinkis darbus, kurie tau tinka.'),E('p',{},'Nurodyk paslaugas ir miestus, kuriuose dirbi. Tinkamus poreikius matysi paskyroje — be masinio kontaktų dalijimo.')),link('Nustatyti veiklą ir teritoriją',{view:'needs',tab:'provider'},'btn primary')));
  return root;
 };
})();