(()=>{
 'use strict';
 const {E,s,pages,link,button,field,form,submit,notice,panel,heading,money,date,toast,api,go,modal}=App;
 const services={moving:'Pervežimas',cleaning:'Valymas',assembly:'Baldų surinkimas'};
 const states={draft:'Juodraštis',pending:'Laukia peržiūros',open:'Priima pasiūlymus',assigned:'Pasirinktas specialistas',closed:'Uždarytas',rejected:'Reikia patikslinti',proposed:'Pasiūlymas',selected:'Pasirinktas',withdrawn:'Atsiimtas',awaiting:'Laukia specialisto patvirtinimo',confirmed:'Abi pusės patvirtino',completed:'Abi pusės pažymėjo užbaigtu',cancelled:'Atšauktas'};
 const tag=value=>E('span',{class:'badge'},states[value]||value);
 const amount=cents=>cents===null||cents===undefined?'Biudžetas derinamas':money(Number(cents)/100);
 const refresh=async()=>{s.dirty=false;await App.render(false);};
 const confirmBox=(name,label)=>E('label',{class:'checkline'},E('input',{type:'checkbox',name,required:true}),E('span',{},label));
 function needCard(n){return E('article',{class:'panel v15-need-card'},E('div',{class:'row between'},E('span',{class:'kicker'},services[n.service]||'Paslaugos'),tag(n.state||'open')),E('h3',{},link(n.title,{view:'need',id:n.id})),E('p',{class:'muted'},n.city+' · '+(n.timing||'')),E('strong',{},amount(n.budget_cents)),n.offer_count!==undefined?E('p',{class:'hint'},'Gautų pasiūlymų: '+n.offer_count):null,link('Atverti poreikį',{view:'need',id:n.id},'btn small'));
 }
 function providerForm(profile){const p=profile||{services:[],cities:[],accepting:false};return form([E('h2',{},'Kokių užklausų ieškai?'),E('p',{class:'muted'},'Rinkis paslaugas ir miestus, kuriuose dirbi. Užklausos rodomos tik prisijungus; asmens kontaktai automatiškai neplatinami.'),E('fieldset',{class:'v15-checkboxes'},E('legend',{},'Teikiamos paslaugos'),Object.entries(services).map(([key,label])=>E('label',{class:'checkline'},E('input',{type:'checkbox',name:'services',value:key,checked:p.services.includes(key)}),E('span',{},label)))),field('cities','Aptarnaujami miestai','text',p.cities.join(', '),{required:true,maxLength:720,placeholder:'Vilnius, Trakai, Kaunas'}),E('p',{class:'hint'},'Iki 12 miestų, atskirtų kableliais. Paieška šiuo metu remiasi miestais, ne kilometrų spinduliu.'),E('label',{class:'checkline'},E('input',{type:'checkbox',name:'accepting',checked:p.accepting}),E('span',{},'Šiuo metu priimu naujas užklausas.')),submit('Išsaugoti veiklą')],async fd=>{const cities=String(fd.get('cities')).split(',').map(v=>v.trim()).filter(Boolean);if(!fd.getAll('services').length)throw new Error('Pasirink bent vieną paslaugą.');if(cities.length>12)throw new Error('Nurodyk iki 12 miestų.');await api('provider-profile',{profile:{services:fd.getAll('services'),cities,accepting:fd.has('accepting')}});toast('Veikla ir teritorija išsaugotos.');await refresh();});}
 pages.needs=async p=>{
  const gate=App.requireUser();if(gate){s.afterAuth={...p};return gate;}
  const data=await api('needs-dashboard');const tab=['provider','offers'].includes(p.tab)?p.tab:'mine';
  const root=E('div',{class:'v15-needs'},heading('Poreikiai ir susitarimai','Vienas darbas, palyginami pasiūlymai ir aiškios sąlygos.'),E('nav',{class:'tabs','aria-label':'Poreikių skyriai'},link('Mano poreikiai',{view:'needs'},tab==='mine'?'active':''),link('Gautos užklausos',{view:'needs',tab:'provider'},tab==='provider'?'active':''),link('Mano pasiūlymai',{view:'needs',tab:'offers'},tab==='offers'?'active':'')),E('div',{class:'actions'},link('＋ Naujas poreikis',{view:'need-new'},'btn primary'),button('Atnaujinti',refresh,'btn'),button('Eksportuoti duomenis',async()=>App.download('telkinys-poreikiai.json',JSON.stringify(await api('needs-export'),null,2),'application/json'),'btn quiet')));
  if(tab==='mine')root.append(data.mine.length?E('div',{class:'v15-grid'},data.mine.map(needCard)):panel(E('h2',{},'Nuo ko pradėsime?'),E('p',{},'Aprašyk pervežimą, valymą ar baldų surinkimą. Poreikį peržiūrės moderatorius. Tinkami specialistai galės pateikti iki penkių pasiūlymų.'),link('Aprašyti poreikį',{view:'need-new'},'btn primary')));
  if(tab==='provider'){
   root.append(E('details',{class:'panel',open:!data.profile?.accepting},E('summary',{},'Veikla, teritorija ir užimtumas'),providerForm(data.profile)),E('h2',{},'Tavo veiklai ir miestams tinkamos užklausos'));
   root.append(data.opportunities.length?E('div',{class:'v15-grid'},data.opportunities.map(needCard)):panel(E('h3',{},data.profile?.accepting?'Tinkamų užklausų kol kas nėra.':'Įjunk naujų užklausų priėmimą.'),E('p',{class:'muted'},data.profile?.accepting?'Patikrink pasirinktus miestus arba sugrįžk vėliau. Užklausų kiekio ir atsakymo termino negarantuojame.':'Pažymėk teikiamas paslaugas ir miestus. Kol priėmimas išjungtas, naujos užklausos nerodomos.')));
  }
  if(tab==='offers')root.append(data.offers.length?E('div',{class:'stack'},data.offers.map(o=>panel(E('div',{class:'row between'},E('h3',{},link(o.title,{view:'need',id:o.need_id})),tag(o.state)),E('p',{},amount(o.amount_cents)+' · '+o.city),E('p',{class:'hint'},'Pasiūlymo galiojimas: '+date(o.valid_until)),link('Pokalbis ir susitarimas',{view:'need',id:o.need_id},'btn small')))):panel(E('h3',{},'Pasiūlymų dar nesiuntei.'),link('Peržiūrėti tinkamus poreikius',{view:'needs',tab:'provider'},'btn')));
  return root;
 };
 pages['need-new']=async p=>{
  let old=null;if(p.id){if(!s.user){s.afterAuth={...p};return App.requireUser();}const data=await api('need-detail',{id:p.id});if(!data.owner)throw new Error('Tai ne tavo poreikis.');old=data.need;}
  const draft=old?{...old,budget:old.budget_cents===null?'':Number(old.budget_cents)/100}:s.needDraft||{title:String(p.q||'').slice(0,120),scope:p.q||'',city:p.city||'',service:services[p.service]?p.service:'moving',timing:'',budget:''};
  const root=E('div',{class:'narrow stack'},heading(old?'Patikslink poreikį':'Ko reikia tavo darbui?','Pradžioje — pervežimas, valymas ir baldų surinkimas. Kitos kategorijos lieka pasiūlymų paieškoje.'),notice('Rašyk darbų apimtį, ne savo kontaktus. Nenurodyk tikslaus adreso, telefono, dokumentų ar kitų jautrių duomenų. Juodraštis matomas tik tau.'));
  const scopeHints={moving:'Ką vežti, kiek daiktų, jų matmenys, aukštai, liftas, ar reikalingi nešėjai. Nenurodyk tikslaus adreso.',cleaning:'Patalpų plotas, kambarių skaičius, valymo tipas, langai, priemonės ir papildomi darbai.',assembly:'Baldų tipas, kiekis, modelis ar matmenys, tvirtinimas prie sienos, ar yra instrukcija.'};
  const help=E('p',{class:'hint'},scopeHints[draft.service]);
  const f=form([E('div',{class:'form-grid'},field('service','Kokios pagalbos reikia?',Object.entries(services),draft.service,{required:true}),field('city','Miestas','text',draft.city,{required:true,minLength:2,maxLength:60,placeholder:'Pvz., Vilnius'})),field('title','Trumpas pavadinimas','text',draft.title,{required:true,minLength:8,maxLength:120,placeholder:'Reikia pervežti sofą Vilniuje'}),field('scope','Kas turi būti atlikta?','textarea',draft.scope,{required:true,minLength:30,maxLength:3000,rows:5}),help,E('div',{class:'form-grid'},field('timing','Pageidaujamas laikas','text',draft.timing,{required:true,minLength:3,maxLength:200,placeholder:'Šeštadienį ryte arba laikas derinamas'}),field('budget','Bendras biudžetas, € (nebūtina)','number',draft.budget,{min:0,max:1e9,step:0.01,inputmode:'decimal'})),confirmBox('share','Suprantu, kad pateikus peržiūrai šį aprašymą galės matyti tinkamos paslaugos ir miesto beta specialistai. Kontaktų neįrašiau.'),submit(s.user?'Išsaugoti juodraštį':'Prisijungti ir išsaugoti')],async fd=>{
   const need={title:String(fd.get('title')),service:String(fd.get('service')),city:String(fd.get('city')),scope:String(fd.get('scope')),timing:String(fd.get('timing')),budget:fd.get('budget')===''?null:Number(fd.get('budget')),share:fd.has('share'),...(old?{id:old.id,version:old.version}:{})};
   if(!s.user){s.needDraft={...need,budget:need.budget??''};s.afterAuth={view:'need-new'};s.dirty=false;go({view:'login'});return;}
   const result=await api('need-save',{need});delete s.needDraft;s.dirty=false;go({view:'need',id:result.id});toast('Juodraštis išsaugotas. Prieš pateikdamas dar peržiūrėk sąlygas.');
  });f.classList.add('panel','stack');f.addEventListener('input',()=>s.dirty=true);f.querySelector('[name=service]').addEventListener('change',e=>help.textContent=scopeHints[e.target.value]);root.append(f);
  if(!s.user)root.append(panel(E('p',{},'Iki prisijungimo įvestas tekstas lieka tik šiame atvertame puslapyje. Perkrovus jis gali būti prarastas.'),link('Neturi kvietimo? Pateik prašymą',{view:'access',kind:'invite'},'btn')));
  return root;
 };
 function quoteFacts(o){return E('dl',{class:'v15-facts'},E('dt',{},'Visa suma'),E('dd',{class:'price'},amount(o.amount_cents)),E('dt',{},'Įskaičiuota'),E('dd',{},o.included),E('dt',{},'Neįskaičiuota / papildomos sąlygos'),E('dd',{},o.exclusions),E('dt',{},'Siūlomas laikas'),E('dd',{},o.timing),E('dt',{},'Pasiūlymas galioja iki'),E('dd',{},date(o.valid_until)));}
 function agreementCard(a,owner){const sn=a.snapshot;const root=E('section',{class:'panel v15-agreement'},E('div',{class:'row between'},E('h2',{},'Susitarimo kortelė'),tag(a.state)),E('p',{class:'hint'},'Nr. '+a.id.slice(0,8)+' · '+date(a.created_at)),E('h3',{},sn.title),E('p',{class:'text-wrap'},sn.scope),quoteFacts({amount_cents:sn.amountCents,included:sn.included,exclusions:sn.exclusions,timing:sn.timing,valid_until:sn.validUntil}),notice('Tai abiejų pusių sutartų sąlygų įrašas. Telkinys nepriima mokėjimo ir negarantuoja paslaugos atlikimo. Sąlygų tekstas po pasirinkimo nekeičiamas.'),button('Išsaugoti sąlygų kopiją',()=>App.download('telkinys-susitarimas-'+a.id.slice(0,8)+'.json',JSON.stringify(a,null,2),'application/json'),'btn'));
  if(a.state==='awaiting')root.append(E('p',{},owner?'Tavo pasirinkimas užfiksuotas. Laukiama specialisto patvirtinimo.':'Užsakovas pasirinko tavo pasiūlymą. Patikrink užfiksuotas sąlygas.'),!owner?button('Patvirtinti šias sąlygas',async()=>{await api('agreement-confirm',{id:a.id});toast('Sąlygos patvirtintos abiejų pusių.');await refresh();},'btn primary'):null);
  if(a.state==='confirmed')root.append(E('p',{class:'hint'},'Užsakovas pažymėjo užbaigtu: '+(a.owner_completed?'taip':'ne')+' · Specialistas: '+(a.provider_completed?'taip':'ne')),!(owner?a.owner_completed:a.provider_completed)?button('Mano pusėje užbaigta',async()=>{if(!confirm('Patvirtinti, kad tavo pusėje darbas užbaigtas? Tai nėra mokėjimo patvirtinimas.'))return;await api('agreement-complete',{id:a.id});await refresh();},'btn primary'):null);
  if(['awaiting','confirmed'].includes(a.state))root.append(button('Atšaukti susitarimą',()=>modal('Atšaukti susitarimą?',notice('Kita pusė matys priežastį. Poreikis bus uždarytas; naujoms sąlygoms sukurk naują poreikį.','warning'),form([field('reason','Atšaukimo priežastis','textarea','',{required:true,minLength:10,maxLength:1000}),submit('Atšaukti susitarimą')],async fd=>{await api('agreement-cancel',{id:a.id,reason:fd.get('reason')});App.$('#dialog').close();await refresh();})),'btn quiet'));
  if(a.cancel_reason)root.append(notice(a.cancel_reason,'warning'));return root;
 }
 pages.need=async p=>{
  const gate=App.requireUser();if(gate){s.afterAuth={...p};return gate;}
  const data=await api('need-detail',{id:p.id}),n=data.need;
  const root=E('div',{class:'v15-need-detail'},heading(n.title,services[n.service]+' · '+n.city),E('div',{class:'row between'},tag(n.state),E('div',{class:'actions'},link('Visi mano poreikiai',{view:'needs'},'btn small'),button('Atnaujinti',refresh,'btn small'))),panel(E('h2',{},'Užduotis'),E('p',{class:'text-wrap'},n.scope),E('dl',{class:'v15-facts'},E('dt',{},'Pageidaujamas laikas'),E('dd',{},n.timing),E('dt',{},'Biudžetas'),E('dd',{},amount(n.budget_cents))),n.moderation_note?notice(n.moderation_note,'warning'):null);
  App.onLive=async()=>toast('Gautas atnaujinimas dėl poreikio. Paspausk „Atnaujinti“.');
  if(data.owner){const actions=E('div',{class:'actions'});
   if(['draft','pending','rejected'].includes(n.state))actions.append(link('Redaguoti',{view:'need-new',id:n.id},'btn'));
   if(['draft','rejected'].includes(n.state))actions.append(button('Pateikti specialistų peržiūrai',()=>modal('Pateikti poreikį?',E('p',{},'Po moderatoriaus peržiūros aprašymas bus matomas tavo miestą ir paslaugą pasirinkusiems beta specialistams. Iki 5 galiojančių pasiūlymų. Atsakymų negarantuojame.'),button('Pateikti',async()=>{await api('need-submit',{id:n.id,version:n.version});App.$('#dialog').close();await refresh();},'btn primary')),'btn primary'));
   if(!['assigned','closed'].includes(n.state))actions.append(button('Uždaryti poreikį',async()=>{if(!confirm('Uždaryti poreikį ir nebepriimti pasiūlymų?'))return;await api('need-close',{id:n.id,version:n.version});await refresh();},'btn quiet'));root.append(actions);
  }
  for(const a of data.agreements)root.append(agreementCard(a,data.owner));
  root.append(E('div',{class:'section-head'},E('h2',{},data.owner?'Gauti pasiūlymai':'Tavo pasiūlymas'),E('span',{class:'hint'},'Galutinė suma · apimtis · laikas')));
  const quotes=E('div',{class:'v15-quotes'});
  for(const o of data.offers){const expired=Date.parse(o.valid_until)<=Date.now();const card=E('article',{class:'panel v15-quote'},E('div',{class:'row between'},E('h3',{},o.provider_name),tag(o.state)),quoteFacts(o),expired&&o.state==='proposed'?notice('Pasiūlymo galiojimas pasibaigė.','warning'):null,n.budget_cents!==null&&Number(o.amount_cents)>Number(n.budget_cents)?notice('Ši suma viršija nurodytą biudžetą.','warning'):null);
   if(data.owner&&n.state==='open'&&o.state==='proposed'&&!expired)card.append(button('Pasirinkti pasiūlymą',()=>modal('Patvirtink pasirinkimą',E('h3',{},o.provider_name),quoteFacts(o),notice('Pasirinkus sąlygos užfiksuojamos ir laukiama specialisto patvirtinimo. Mokėjimas neatliekamas.'),button('Pasirinkti šias sąlygas',async()=>{await api('need-select',{offerId:o.id});App.$('#dialog').close();await refresh();},'btn primary')),'btn primary wide'));
   if(!data.owner&&o.state==='proposed')card.append(button('Atsiimti pasiūlymą',async()=>{if(!confirm('Atsiimti pasiūlymą? Šiame etape vienam poreikiui teikiamas vienas pasiūlymas.'))return;await api('need-withdraw',{id:o.id});await refresh();},'btn quiet'));
   const messages=data.messages.filter(m=>m.offer_id===o.id);
   const talk=E('details',{class:'v15-discussion',open:data.offers.length===1},E('summary',{},'Privatus aptarimas ('+messages.length+')'),E('p',{class:'hint'},'Šį aptarimą mato tik poreikio autorius ir šio pasiūlymo specialistas. Rodomi naujausi pranešimai.'),E('div',{class:'stack'},messages.map(m=>E('div',{class:'v15-message '+(m.sender_id===s.user.id?'mine':'')},E('strong',{},m.sender_id===s.user.id?'Tu':data.owner?o.provider_name:n.owner_name),E('p',{class:'text-wrap'},m.body),E('small',{class:'muted'},date(m.created_at))))));
   let clientId=crypto.randomUUID();talk.append(form([field('body','Žinutė','textarea','',{required:true,minLength:1,maxLength:2000,rows:3,placeholder:'Patikslink apimtį ar laiką.'}),submit('Siųsti')],async fd=>{await api('need-message',{offerId:o.id,body:fd.get('body'),clientId});clientId=crypto.randomUUID();await refresh();}));card.append(talk);quotes.append(card);
  }
  if(data.offers.length)root.append(quotes);else root.append(E('p',{class:'muted'},data.owner?'Pasiūlymų dar nėra. Jie atsiras čia, kai tinkami specialistai atsakys.':'Gali pateikti vieną aiškų pasiūlymą. Kitų specialistų kainų nematysi.'));
  if(!data.owner&&!data.offers.length&&n.state==='open'){
   const expires=new Date(Date.now()+2*86400000);const localTime=new Date(expires.getTime()-expires.getTimezoneOffset()*60000).toISOString().slice(0,16);
   root.append(E('section',{class:'panel stack'},E('h2',{},'Pateik palyginamą pasiūlymą'),form([field('amount','Galutinė bendra suma, €','number','',{required:true,min:0,max:1e9,step:0.01,inputmode:'decimal'}),field('included','Kas įskaičiuota?','textarea','',{required:true,minLength:10,maxLength:1200,rows:3}),field('exclusions','Kas neįskaičiuota / kokios papildomos sąlygos?','textarea','',{required:true,minLength:2,maxLength:800,placeholder:'Jei papildomų sąlygų nėra, taip ir parašyk.'}),field('timing','Siūlomas laikas','text','',{required:true,minLength:3,maxLength:200}),field('validUntil','Iki kada galioja pasiūlymas? (tavo įrenginio laiku)','datetime-local',localTime,{required:true}),confirmBox('totalConfirmed','Nurodžiau visą sumą už išvardytus darbus su taikomais mokesčiais. Papildomas sąlygas atskleidžiau.'),submit('Siųsti pasiūlymą')],async fd=>{await api('need-offer',{offer:{needId:n.id,amount:Number(fd.get('amount')),included:String(fd.get('included')),exclusions:String(fd.get('exclusions')),timing:String(fd.get('timing')),validUntil:new Date(String(fd.get('validUntil'))).toISOString(),totalConfirmed:fd.has('totalConfirmed')}});toast('Pasiūlymas išsiųstas.');await refresh();})));
  }
  root.append(link('Reikia pagalbos dėl šio poreikio?',{view:'access',kind:'help',q:'Poreikio numeris: '+n.id+'\n'},'btn quiet'));return root;
 };
})();