(()=>{
 const {E,s,pages,categories,link,button,field,form,submit,notice,panel,empty,heading,badge,money,date,toast,api,go,modal}=App;
 async function acceptSession(result){App.setToken(result.token);s.user=result.user;await App.refreshMe();App.connectLive();const next=s.afterAuth||{view:'account'};delete s.afterAuth;
  if(result.recoveryCode){const code=result.recoveryCode;modal('Išsaugok paskyros atkūrimo kodą.',E('p',{},'Šis kodas parodomas tik dabar. Jis leis pakeisti pamirštą slaptažodį. Beta versijoje atkūrimo el. laiškų nesiunčiame.'),E('code',{class:'secure-code'},code),notice('Laikyk slaptažodžių tvarkyklėje. Nesiųsk šio kodo kitiems.','warning'),E('div',{class:'actions'},button('Išsaugoti kodą faile',()=>App.download('telkinys-atkurimo-kodas.txt','Prisijungimo vardas: '+result.user.username+'\nAtkūrimo kodas: '+code+'\nSaugok privačiai. Po panaudojimo kodas pakeičiamas nauju.\n')),button('Išsaugojau — tęsti',()=>{App.$('#dialog').close();go(next);},'btn primary')));}else go(next);
 }
 pages.login=async p=>{
  const mode=['signup','recover'].includes(p.mode)?p.mode:'login';
  const root=E('section',{class:'auth panel'},E('span',{class:'kicker'},'Mano Telkinys'),E('h1',{},mode==='signup'?'Prisijunk prie beta.':mode==='recover'?'Atkurk paskyrą.':'Gera vėl matyti.'),E('div',{class:'tabs'},link('Prisijungti',{view:'login'},mode==='login'?'active':''),link('Registruotis',{view:'login',mode:'signup'},mode==='signup'?'active':''),link('Atkurti',{view:'login',mode:'recover'},mode==='recover'?'active':'')));
  if(s.user&&mode!=='recover'){root.append(notice('Jau prisijungta: '+s.user.displayName),link('Atidaryti paskyrą',{view:'account'},'btn primary wide'));return root;}
  const fields=[field('username','Prisijungimo vardas','text','',{required:true,minLength:3,maxLength:30,pattern:'[a-z0-9_]{3,30}',autocomplete:'username',autocapitalize:'none',spellcheck:'false',placeholder:'pvz., vardas_123'}),E('p',{class:'hint'},'3–30 mažųjų lotyniškų raidžių, skaitmenų arba _. El. pašto adresas nereikalingas.')];
  if(mode==='signup')fields.push(field('displayName','Viešai rodomas vardas','text','',{required:true,minLength:2,maxLength:70,autocomplete:'nickname'}),field('invite','Kvietimo kodas','text','',{required:true,minLength:20,maxLength:100,autocomplete:'off',autocapitalize:'none'}));
  if(mode==='recover')fields.push(field('recoveryCode','Vienkartinis atkūrimo kodas','text','',{required:true,minLength:20,maxLength:100,autocomplete:'off',autocapitalize:'none'}));
  fields.push(field('password',mode==='recover'?'Naujas slaptažodis':'Slaptažodis','password','',{required:true,minLength:mode==='login'?1:12,maxLength:128,autocomplete:mode==='login'?'current-password':'new-password'}));
  if(mode!=='login')fields.push(field('repeat','Pakartok slaptažodį','password','',{required:true,minLength:12,maxLength:128,autocomplete:'new-password'}),E('p',{class:'hint'},'Bent 12 simbolių. Naudok unikalų slaptažodį.'));
  if(mode==='signup')fields.push(E('label',{class:'checkline'},E('input',{type:'checkbox',name:'terms',required:true}),E('span',{},'Susipažinau su ',link('beta taisyklėmis',{view:'terms'}),' ir ',link('privatumo informacija',{view:'privacy'}),'. Suprantu, kad tai riboto naudojimo beta versija.')));
  fields.push(submit(mode==='signup'?'Sukurti paskyrą':mode==='recover'?'Atkurti prieigą':'Prisijungti'));
  root.append(form(fields,async fd=>{if(mode!=='login'&&fd.get('password')!==fd.get('repeat'))throw new Error('Slaptažodžiai nesutampa.');const result=await api(mode==='signup'?'signup':mode==='recover'?'recover':'login',{username:fd.get('username'),password:fd.get('password'),...(mode==='signup'?{displayName:fd.get('displayName'),invite:fd.get('invite'),terms:fd.has('terms')}:{}) ,...(mode==='recover'?{recoveryCode:fd.get('recoveryCode')}:{})});await acceptSession(result);}));
  root.append(notice('Registracija tik su kvietimu. Šiuo metu nenaudojame el. pašto patvirtinimų, o viešai rodomas vardas nėra tapatybės patikra.'));return root;
 };
 pages.account=async p=>{
  const gate=App.requireUser();if(gate){s.afterAuth={...p};return gate;}await App.refreshMe();
  const tabs={listings:'Mano skelbimai',saved:'Išsaugota',messages:'Žinutės',calendar:'Kalendorius',profile:'Nustatymai',support:'Pagalba'};if(['admin','moderator'].includes(s.user.role))tabs.admin='Administravimas';
  const tab=Object.hasOwn(tabs,p.tab)?p.tab:'listings';const root=E('div',{},heading('Tavo Telkinys',s.user.displayName+' · @'+s.user.username),E('nav',{class:'tabs','aria-label':'Paskyros skyriai'},Object.entries(tabs).map(([key,label])=>link(label,{view:'account',tab:key},tab===key?'active':''))));
  if(tab==='listings'){
   const data=await api('my-listings');root.append(E('div',{class:'section-head'},E('h2',{},'Mano pasiūlymai'),link('＋ Naujas pasiūlymas',{view:'edit'},'btn primary')));
   if(!data.items.length)root.append(empty('Dar neturi pasiūlymų.','Sukurk pirmą skelbimą. Jis bus išsaugotas kaip juodraštis, o prieš viešinimą peržiūrėtas.',link('Sukurti skelbimą',{view:'edit'},'btn primary')));
   else root.append(E('div',{class:'workspace'},data.items.map(item=>panel(E('div',{class:'inventory-row'},E('div',{},E('h3',{},item.title),E('div',{class:'inventory-meta'},badge(item.status),E('span',{},money(item.price,item.priceUnit)),E('span',{},item.city)),item.moderationNote?notice(item.moderationNote,'warning'):null),E('div',{class:'actions'},link('Redaguoti',{view:'edit',id:item.id},'btn small'),item.status==='active'?link('Atverti',{skelbimas:item.id},'btn small'):null,button(item.status==='active'?'Sustabdyti':'Pateikti peržiūrai',async()=>{await api('set-status',{id:item.id,version:item.version,status:item.status==='active'?'paused':'pending'});await App.render(false);},'btn small'),item.status!=='completed'?button('Užbaigti',async()=>{if(!confirm('Pažymėti pasiūlymą užbaigtu ir neberodyti paieškoje?'))return;await api('set-status',{id:item.id,version:item.version,status:'completed'});await App.render(false);},'btn small'):null))))));
  }else if(tab==='saved'){
   root.append(E('div',{class:'section-head'},E('h2',{},'Išsaugotos paieškos')));
   const searches=s.me.searches||[];
   if(searches.length)root.append(E('div',{class:'stack'},searches.map(x=>panel(E('div',{class:'row between'},link(x.name,x.filters,'btn quiet'),button('Pašalinti',async()=>{await api('delete-search',{id:x.id});await App.render(false);},'btn small'))))));else root.append(E('p',{class:'muted'},'Paiešką gali išsaugoti rezultatų puslapyje.'));
   root.append(E('div',{class:'section-head'},E('h2',{},'Patikę pasiūlymai')));const data=await api('favorites');root.append(data.items.length?E('div',{class:'grid'},data.items.map(App.card)):empty('Dar nieko neišsaugojai.','Prie patikusio pasiūlymo paspausk širdelę. Išsaugoti pasiūlymai bus matomi ir kitame įrenginyje.',link('Ieškoti',{},'btn primary')));
  }else if(tab==='messages')root.append(await App.inboxPane());
  else if(tab==='calendar')root.append(await App.calendarPane());
  else if(tab==='profile'){
   root.append(E('div',{class:'narrow stack'},panel(E('h2',{},'Paskyros duomenys'),form([field('displayName','Viešai rodomas vardas','text',s.user.displayName,{required:true,minLength:2,maxLength:70}),submit('Išsaugoti vardą')],async fd=>{await api('profile',{displayName:fd.get('displayName')});await App.refreshMe();toast('Vardas išsaugotas.');})),panel(E('h2',{},'Slaptažodis ir sesijos'),E('p',{class:'muted'},'Pakeitus slaptažodį, kiti įrenginiai bus atjungti. Gausi naują atkūrimo kodą.'),form([field('password','Dabartinis slaptažodis','password','',{required:true,maxLength:128,autocomplete:'current-password'}),field('newPassword','Naujas slaptažodis','password','',{required:true,minLength:12,maxLength:128,autocomplete:'new-password'}),field('repeat','Pakartok naują slaptažodį','password','',{required:true,minLength:12,maxLength:128,autocomplete:'new-password'}),submit('Pakeisti slaptažodį')],async fd=>{if(fd.get('newPassword')!==fd.get('repeat'))throw new Error('Slaptažodžiai nesutampa.');const result=await api('password',{password:fd.get('password'),newPassword:fd.get('newPassword')});s.afterAuth={view:'account',tab:'profile'};await acceptSession(result);})),panel(E('h2',{},'Tavo duomenys'),E('p',{class:'muted'},'Gauk paskyros, pasiūlymų ir pokalbių kopiją. Nuotraukų originalus saugok ir savo įrenginyje.'),E('div',{class:'actions'},button('Eksportuoti mano duomenis',async()=>{const data=await api('export');App.download('telkinys-mano-duomenys.json',JSON.stringify(data,null,2),'application/json');}),button('Atsijungti',async()=>{await api('logout');App.setToken('');s.user=null;s.me=null;App.updateHeader();go({});})),s.user.role!=='admin'?button('Ištrinti paskyrą',()=>{modal('Negrįžtamai ištrinti paskyrą?',notice('Bus ištrinti tavo skelbimai, išsaugojimai ir su paskyra susiję pokalbiai. Pirma pasiimk duomenų kopiją. Veiksmo atšaukti negalima.','warning'),form([field('password','Patvirtink dabartiniu slaptažodžiu','password','',{required:true,maxLength:128,autocomplete:'current-password'}),submit('Ištrinti mano paskyrą','',false)],async fd=>{await api('delete-account',{password:fd.get('password')});App.setToken('');s.user=null;s.me=null;App.updateHeader();App.$('#dialog').close();go({});toast('Paskyra ištrinta.');}));},'btn danger wide'):null)));
  }else if(tab==='support'){
   root.append(panel(E('h2',{},'Parašyk projekto administratoriui.'),E('p',{class:'muted'},'Atsakymą rasi čia ir paskyros pranešimuose. El. paštu pranešimų nesiunčiame.'),form([field('topic','Tema',[['help','Pagalba'],['bug','Klaida'],['privacy','Privatumas'],['deletion','Duomenų ištrynimas']],'help'),field('body','Užklausa','textarea','',{required:true,minLength:10,maxLength:3000}),submit('Pateikti užklausą')],async fd=>{await api('ticket',{topic:fd.get('topic'),body:fd.get('body')});toast('Užklausa pateikta.');await App.render(false);})));const data=await api('my-tickets');root.append(E('div',{class:'stack'},data.tickets.map(t=>panel(E('div',{class:'row between'},E('strong',{},t.resolved?'Atsakyta':'Laukiama atsakymo'),E('small',{class:'muted'},date(t.created_at))),E('p',{class:'text-wrap'},t.body),t.reply?notice(t.reply):null))));
  }else if(tab==='admin')root.append(await App.adminPane());
  return root;
 };
 pages.edit=async p=>{
  const gate=App.requireUser();if(gate){s.afterAuth={...p};return gate;}
  let item=p.id?await api('listing',{id:p.id}):null;
  if(item&&item.ownerId!==s.user.id)throw new Error('Šis skelbimas priklauso kitam vartotojui.');
  const images=item?(await api('private-images',{id:item.id})).images:[];
  let version=item?.version;
  const root=E('div',{class:'narrow'},heading(item?'Redaguok pasiūlymą.':'Ką nori pasiūlyti?','Tikras pasiūlymas, vienas įrašas. Bazinis įkėlimas nemokamas.'));
  if(item)root.append(badge(item.status));if(item?.moderationNote)root.append(notice(item.moderationNote,'warning'));
  const optionalAttributes=E('div',{class:'form-grid'},field('rooms','Kambarių skaičius','number',item?.attributes.rooms??'',{min:1,max:30,step:1}),field('floor','Aukštas','number',item?.attributes.floor??'',{min:-2,max:200,step:1}),field('area','Plotas, m²','number',item?.attributes.area??'',{min:0.01,max:1e7,step:0.01}),field('year','Metai','number',item?.attributes.year??'',{min:1800,max:new Date().getFullYear()+1,step:1}),field('brand','Automobilio markė','text',item?.attributes.brand??'',{maxLength:40}),field('model','Modelis','text',item?.attributes.model??'',{maxLength:70}),field('mileage','Rida, km','number',item?.attributes.mileage??'',{min:0,max:5000000,step:1}),field('condition','Būklė',[['','Nenurodyta'],['new','Nauja'],['used','Naudota'],['renovated','Renovuota'],['other','Kita']],item?.attributes.condition??''));
  const photos=E('div',{class:'photo-grid'},images.map(image=>E('div',{class:'photo-tile'},E('img',{src:image.url,alt:'Tavo skelbimo nuotrauka'}),button('Pašalinti',async(e,b)=>{await api('delete-image',{id:image.id});b.closest('.photo-tile').remove();const fresh=await api('listing',{id:item.id});version=fresh.version;toast('Nuotrauka pašalinta.');},'btn small')))));
  const f=form([E('div',{class:'form-grid'},field('category','Kategorija',Object.entries(categories),item?.category||'items',{required:true}),field('priceUnit','Kainos vienetas',[['total','Visa suma'],['hour','Už valandą'],['month','Už mėnesį'],['from','Kaina nuo'],['negotiable','Sutartinė']],item?.priceUnit||'total'),field('title','Pavadinimas','text',item?.title||'',{required:true,minLength:8,maxLength:120}),field('price','Kaina, €','number',item?.price??'',{required:true,min:0,max:1e9,step:0.01,inputmode:'decimal'}),field('city','Miestas','text',item?.city||'',{required:true,minLength:2,maxLength:60,placeholder:'Pvz., Vilnius'}),field('district','Rajonas / vietovė','text',item?.district||'',{maxLength:80,placeholder:'Pvz., Žirmūnai'})),field('description','Aprašymas','textarea',item?.description||'',{required:true,minLength:30,maxLength:6000,placeholder:'Aprašyk pasiūlymą, būklę, kas įskaičiuota ir svarbias sąlygas. Kontaktus pateik pokalbyje, o ne viešame tekste.'}),E('details',{class:'form-section',open:!!item&&Object.keys(item.attributes||{}).length>0},E('summary',{},'Papildomi paieškos kriterijai'),E('p',{class:'hint'},'Užpildyk tik savo kategorijai tinkamus laukus. Paieška tikrina nurodytus skaičius, o ne spėja iš aprašymo.'),optionalAttributes),E('section',{class:'form-section'},E('h3',{},'Nuotraukos'),E('p',{class:'hint'},'Iki 6 nuotraukų. JPEG, PNG arba WebP, iki 3 MB kiekviena. Įkeliant pašalinami metaduomenys. Būstui, auto ir daiktams prieš viešinimą reikia bent vienos nuotraukos.'),photos,field('photos','Pridėti nuotraukų','file','',{multiple:true,accept:'image/jpeg,image/png,image/webp'})),notice('Naują ar pakeistą viešą skelbimą peržiūri moderatorius. Patvirtinimo būsena bus matoma paskyroje.'),E('div',{class:'actions'},submit('Išsaugoti juodraštį','draft',false),submit('Pateikti publikavimui','publish'))],async(fd,intent,f)=>{
   const files=fd.getAll('photos').filter(x=>x instanceof File&&x.size);for(const file of files){if(file.size>3000000)throw new Error('Kiekviena nuotrauka turi būti iki 3 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Leidžiamos JPEG, PNG ir WebP nuotraukos.');}
   const attrs={};for(const key of ['rooms','floor','area','year','mileage']){const value=fd.get(key);if(value!=='')attrs[key]=Number(value);}for(const key of ['brand','model','condition']){const value=String(fd.get(key)||'').trim();if(value)attrs[key]=value;}
   const listing={category:fd.get('category'),title:fd.get('title'),description:fd.get('description'),city:fd.get('city'),district:fd.get('district'),price:Number(fd.get('price')),priceUnit:fd.get('priceUnit'),attributes:attrs,...(item?{id:item.id,version}:{})};
   const saved=await api('save-listing',{listing});item={...listing,id:saved.id};version=saved.version;
   for(const file of files){let uploadId;try{const upload=await api('image-upload-url',{listingId:item.id,contentType:file.type,size:file.size});uploadId=upload.id;if(new URL(upload.presignedUrl).protocol!=='https:')throw new Error('Netinkamas įkėlimo adresas.');const res=await fetch(upload.presignedUrl,{method:'PUT',headers:upload.headers,body:file,credentials:'omit'});if(!res.ok)throw new Error('Nuotraukos įkėlimas nepavyko.');await api('image-finalize',{id:upload.id});}catch(err){if(uploadId)await api('delete-image',{id:uploadId}).catch(()=>{});version=(await api('listing',{id:item.id})).version;throw new Error('Juodraštis išsaugotas, bet nepavyko įkelti nuotraukos: '+err.message);}}
   const fresh=await api('listing',{id:item.id});version=fresh.version;
   if(intent==='publish')await api('set-status',{id:item.id,version,status:'pending'});
   s.dirty=false;toast(intent==='publish'?'Pasiūlymas perduotas peržiūrai.':'Juodraštis išsaugotas.');go({view:'account',tab:'listings'});
  });f.classList.add('panel','stack');f.addEventListener('input',()=>s.dirty=true);
  const categoryControl=f.querySelector('[name=category]');categoryControl.addEventListener('change',()=>{if(categoryControl.value==='jobs')f.querySelector('[name=priceUnit]').value='month';});
  root.append(f);if(item)root.append(E('div',{class:'actions'},button('Ištrinti skelbimą',async()=>{if(!confirm('Ištrinti skelbimą? Pokalbių turintį pasiūlymą galima tik užbaigti.'))return;await api('delete-listing',{id:item.id});s.dirty=false;go({view:'account',tab:'listings'});},'btn danger')));return root;
 };
})();
