// Runs inside the build's private scope after the pure search/model functions.
const $ = (selector,root=document)=>root.querySelector(selector);
const $$ = (selector,root=document)=>Array.from(root.querySelectorAll(selector));
const baseTitle=document.title;
const demos=v14PrepareCatalog(catalog);
const iconNames={home:'home',auto:'car',items:'box',services:'tool',jobs:'briefcase',prices:'price'};
let workspace=v14ValidWorkspace(null), storageProblem='';
try { const raw=localStorage.getItem(V14_STORAGE);workspace=v14ValidWorkspace(raw?JSON.parse(raw):null); }
catch { storageProblem='Naršyklės saugykla nepasiekiama arba jos įrašai pažeisti. Nauji įrašai nebus pažymėti išsaugotais, jei išsaugoti nepavyks.'; }
let view={query:'',filters:{category:'',city:'',min:'',max:'',sort:'relevance'},limit:6};
let comparing=new Set(),selectedId=null,spaceTab='saved',editingId=null,editingImages=[],imageBusy=false,editSession=0,pendingDelete=null;
const allRecords=()=>[...demos,...workspace.records];
const findRecord=id=>allRecords().find(x=>x.id===id);
function el(tag,className='',text) { const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=String(text);return n; }
function icon(name) {const n=document.createElementNS('http://www.w3.org/2000/svg','svg');n.setAttribute('class','icon');n.setAttribute('aria-hidden','true');const use=document.createElementNS(n.namespaceURI,'use');use.setAttribute('href','#i-'+name);n.append(use);return n;}
function action(text,name,id,className='btn'){const b=el('button',className,text);b.type='button';b.dataset.action=name;if(id!==undefined)b.dataset.id=id;return b;}
function iconAction(label,name,id,glyph,active=false){const b=action('',name,id,'icon-button'+(active?' active':''));b.setAttribute('aria-label',label);b.setAttribute('aria-pressed',String(active));b.append(icon(glyph));return b;}
function money(x){const format=n=>new Intl.NumberFormat('lt-LT',{maximumFractionDigits:2}).format(n);return format(x.amount)+(x.upper?'–'+format(x.upper):'')+(x.unit==='€'?' €':'');}
function factsFor(x){const f=x.own?{}:{...x.facts};if(x.rooms)f.Kambariai=String(x.rooms);if(x.floor)f.Aukštas=String(x.floor);if(x.year)f.Metai=String(x.year);if(x.mileage!==null&&x.mileage!==undefined)f.Rida=Number(x.mileage).toLocaleString('lt-LT')+' km';if(x.district)f.Rajonas=x.district;return f;}
function renderFacts(x){const dl=el('dl','facts');for(const [key,value] of Object.entries(factsFor(x))){const row=el('div','fact');row.append(el('dt','',key),el('dd','',value));dl.append(row);}return dl;}
function notice(message){const n=$('#toast');n.textContent=message;n.hidden=false;try{if(n.showPopover){n.setAttribute('popover','manual');if(!n.matches(':popover-open'))n.showPopover();}}catch{}clearTimeout(notice.timer);notice.timer=setTimeout(()=>{try{if(n.matches(':popover-open'))n.hidePopover();}catch{}n.hidden=true;},4200);}
function commit(next){try{const clean=v14ValidWorkspace(next);localStorage.setItem(V14_STORAGE,JSON.stringify(clean));workspace=clean;return true;}catch{notice('Nepavyko išsaugoti. Naršyklės saugykla pilna arba užblokuota. Sumažink nuotraukų skaičių arba eksportuok ir atlaisvink vietą.');return false;}}
function showDialog(id){const d=$(id);if(!d.open)d.showModal();}
function updateCounts(){$('#spaceCount').textContent=workspace.favorites.length+workspace.records.length+workspace.searches.length;$('#saveSearch').disabled=!view.query&&!view.filters.category&&!view.filters.city&&view.filters.min===''&&view.filters.max==='';}
function snapshotFrom(raw){const f=raw?.filters||{};return {query:typeof raw?.query==='string'?raw.query.slice(0,250):'',filters:{category:Object.hasOwn(V14_CATEGORIES,f.category)?f.category:'',city:typeof f.city==='string'?f.city.slice(0,80):'',min:f.min!==''&&f.min!==null&&f.min!==undefined&&Number.isFinite(Number(f.min))&&Number(f.min)>=0?String(f.min):'',max:f.max!==''&&f.max!==null&&f.max!==undefined&&Number.isFinite(Number(f.max))&&Number(f.max)>=0?String(f.max):'',sort:['relevance','newest','price-asc','price-desc'].includes(f.sort)?f.sort:'relevance'}};}
function readRoute(){const p=new URL(location.href).searchParams;view={...snapshotFrom({query:p.get('q')||'',filters:{category:p.get('category'),city:p.get('city'),min:p.get('min')??'',max:p.get('max')??'',sort:p.get('sort')}}),limit:6};}
function routeURL(){const u=new URL(location.pathname,location.origin);if(view.query)u.searchParams.set('q',view.query);for(const [key,value] of Object.entries(view.filters))if(value!==''&&!(key==='sort'&&value==='relevance'))u.searchParams.set(key,value);return u;}
function syncInputs(){ $('#query').value=view.query;$('#category').value=view.filters.category;const city=$('#city');const desired=view.filters.city;if(desired&&!Array.from(city.options).some(o=>o.value===desired)){const o=el('option','',desired);o.value=desired;city.append(o);}city.value=desired;$('#minPrice').value=view.filters.min;$('#maxPrice').value=view.filters.max;$('#sort').value=view.filters.sort;}
function applySearch(scroll=false){if(!$('#filterForm').checkValidity()){$('#filterForm').reportValidity();return;}const min=$('#minPrice').value,max=$('#maxPrice').value;const bad=min!==''&&max!==''&&Number(min)>Number(max);$('#filterError').hidden=!bad;if(bad){$('#filterError').textContent='Kaina „nuo“ negali būti didesnė už kainą „iki“.';return;}view={query:$('#query').value.trim().slice(0,250),filters:{category:$('#category').value,city:$('#city').value,min,max,sort:$('#sort').value},limit:6};history.replaceState(null,'',routeURL());renderResults();if(scroll){$('#results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#resultsTitle').focus({preventScroll:true});}}
function resetSearch(){view={query:'',filters:{category:'',city:'',min:'',max:'',sort:'relevance'},limit:6};syncInputs();applySearch();}
function querySearch(query){view.query=query;view.filters={category:'',city:'',min:'',max:'',sort:'relevance'};syncInputs();applySearch(true);}
function renderCard(x){const article=el('article','result-card');article.dataset.id=x.id;const url=routeURL();url.searchParams.set('skelbimas',x.id);const visual=el('a','card-visual tone-'+x.type);visual.href=url;visual.dataset.open=x.id;visual.setAttribute('aria-label','Atidaryti '+x.title);if(x.images.length){const image=el('img');image.src=x.images[0];image.alt=x.title;image.loading='lazy';visual.append(image);}else visual.append(icon(iconNames[x.type]));const copy=el('div','card-copy');copy.append(el('p','card-meta',V14_CATEGORIES[x.type]+' · '+x.loc));const heading=el('h3');const link=el('a','',x.title);link.href=url;link.dataset.open=x.id;heading.append(link);copy.append(heading,el('p','card-description',x.desc),el('span',x.demo?'demo-tag':'local-tag',x.demo?'Demonstracinis pasiūlymas':'Tik šioje naršyklėje'));const aside=el('div','card-aside');const price=el('div','card-price',money(x));if(x.unit!=='€')price.append(el('span','card-unit',x.unit));const buttons=el('div','card-actions');const saved=workspace.favorites.includes(x.id);buttons.append(iconAction(saved?'Pašalinti iš išsaugotų':'Išsaugoti pasiūlymą','favorite',x.id,'bookmark',saved),iconAction('Pridėti palyginimui','compare',x.id,'compare',comparing.has(x.id)));aside.append(price,buttons);article.append(visual,copy,aside);return article;}
function renderResults(){const data=v14Search(allRecords(),view.query,view.filters);const root=$('#resultList');root.replaceChildren(...data.items.slice(0,view.limit).map(renderCard));$('#resultCount').textContent='Rasta: '+data.items.length;$('#emptyResults').hidden=data.items.length!==0;$('#showMore').hidden=data.items.length<=view.limit;const local=data.items.filter(x=>x.own).length;$('#dataNote').textContent=local?'Vietinių: '+local+' · pavyzdinių: '+(data.items.length-local):'Pavyzdiniai pasiūlymai';$('#resultsTitle').textContent=view.query?'Rezultatai pagal tavo paiešką.':'Pasiūlymai vienoje vietoje.';const chips=[...data.criteria];if(view.filters.category&&!chips.includes(V14_CATEGORIES[view.filters.category]))chips.push(V14_CATEGORIES[view.filters.category]);if(view.filters.city&&!chips.includes(view.filters.city))chips.push(view.filters.city);if(view.filters.min!=='')chips.push('Filtras nuo '+view.filters.min+' €');if(view.filters.max!=='')chips.push('Filtras iki '+view.filters.max+' €');$('#criteria').replaceChildren(...chips.map(c=>el('span','',c)));$('#searchWarning').hidden=data.warnings.length===0;$('#searchWarning').textContent=data.warnings.join(' ');for(const c of $$('.category-card')){c.classList.toggle('active',c.dataset.category===(view.filters.category||data.parsed.category));c.setAttribute('aria-pressed',String(c.classList.contains('active')));}updateCounts();}
function refresh(){renderResults();if($('#spaceDialog').open)renderSpace();updateCompareTray();}
function toggleFavorite(id){if(!findRecord(id))return;const has=workspace.favorites.includes(id);if(commit({...workspace,favorites:has?workspace.favorites.filter(x=>x!==id):[...workspace.favorites,id]})){refresh();if(selectedId===id&&$('#detailDialog').open)renderDetail(findRecord(id));notice(has?'Pašalinta iš išsaugotų.':'Išsaugota šioje naršyklėje.');}}
function toggleCompare(id){const x=findRecord(id);if(!x)return;if(comparing.has(id)){comparing.delete(id);refresh();return;}if(comparing.size>=3){notice('Vienu metu galima palyginti iki 3 pasiūlymų.');return;}const first=findRecord([...comparing][0]);if(first&&first.type!==x.type){notice('Palyginimui rinkis tos pačios kategorijos pasiūlymus.');return;}comparing.add(id);refresh();}
function updateCompareTray(){comparing=new Set([...comparing].filter(id=>findRecord(id)?.status==='active'));$('#compareTray').hidden=comparing.size===0;$('#compareCount').textContent='Palyginimui: '+comparing.size+' / 3';$('#openCompare').disabled=comparing.size<2;}
function renderCompare(){if(comparing.size<2)return;const root=$('#compareContent');root.replaceChildren();const items=[...comparing].map(findRecord);const keys=[...new Set(items.flatMap(x=>Object.keys(factsFor(x))))];for(const x of items){const a=el('article');a.append(el('h3','',x.title),el('span',x.demo?'demo-tag':'local-tag',x.demo?'Demonstracinis':'Vietinis pasiūlymas'));const dl=el('dl','facts');const info={'Kaina':money(x)+(x.unit!=='€'?' '+x.unit:''),'Vieta':x.loc};for(const key of keys)info[key]=factsFor(x)[key]??'Nenurodyta';for(const [key,value] of Object.entries(info)){const row=el('div','fact');row.append(el('dt','',key),el('dd','',value));dl.append(row);}a.append(dl);root.append(a);}showDialog('#compareDialog');}
function renderDetail(x){const root=$('#detailContent');root.replaceChildren();const title=el('h2','',x.title);title.id='detailTitle';root.append(el('span',x.demo?'demo-tag':'local-tag',x.demo?'Demonstracinis pasiūlymas':'Vietinis pasiūlymas'),title,el('p','detail-location',V14_CATEGORIES[x.type]+' · '+x.loc),el('div','detail-price',money(x)+(x.unit!=='€'?' '+x.unit:'')));if(x.images.length){const gallery=el('div','detail-gallery');for(const src of x.images){const img=el('img');img.src=src;img.alt=x.title;gallery.append(img);}root.append(gallery);}root.append(el('p','detail-description',x.desc),renderFacts(x));root.append(el('p','notice',x.demo?'Tai pavyzdinis įrašas paieškai išbandyti, ne aktyvus pardavėjo pasiūlymas. Susisiekimas, rezervacijos ir mokėjimai dar neprijungti.':'Šis pasiūlymas saugomas tik tavo naršyklėje. Kitas žmogus jo dar nemato; bendras publikavimas bus prijungtas atskirame etape.'));const actions=el('div','form-actions');actions.append(action(workspace.favorites.includes(x.id)?'Pašalinti iš išsaugotų':'Išsaugoti','favorite',x.id));if(x.own)actions.append(action('Redaguoti','edit',x.id,'btn primary'));else actions.append(action('Kopijuoti peržiūros nuorodą','share',x.id));root.append(actions);document.title=x.title+' · Telkinys V14';}
function openDetail(id,push=true){const x=findRecord(id);if(!x){notice('Pasiūlymo šioje naršyklėje neradome. Vietiniai pasiūlymai nesinchronizuojami tarp įrenginių.');return;}selectedId=id;renderDetail(x);showDialog('#detailDialog');if(push){const u=routeURL();u.searchParams.set('skelbimas',id);history.pushState({listing:id},'',u);}}
async function share(id){const x=findRecord(id);if(!x||x.own){notice('Vietinių pasiūlymų kiti žmonės dar negali atidaryti.');return;}const u=routeURL();u.searchParams.set('skelbimas',id);try{await navigator.clipboard.writeText(String(u));notice('Peržiūros nuoroda nukopijuota.');}catch{const field=el('input');field.value=String(u);field.readOnly=true;field.setAttribute('aria-label','Peržiūros nuoroda kopijavimui');$('#detailContent').append(field);field.select();}}
function renderSpace(){const root=$('#spaceContent');root.replaceChildren();for(const tab of $$('[data-space]')){tab.classList.toggle('active',tab.dataset.space===spaceTab);tab.setAttribute('aria-pressed',String(tab.dataset.space===spaceTab));}if(spaceTab==='saved'){const items=workspace.favorites.map(findRecord).filter(x=>x&&x.status==='active');if(items.length)root.append(...items.map(renderCard));else root.append(el('p','empty','Dar nieko neišsaugojai. Paspausk žymelę prie patikusio pasiūlymo.'));}else if(spaceTab==='listings'){root.append(action('＋ Naujas vietinis pasiūlymas','new',undefined,'btn primary'));if(!workspace.records.length)root.append(el('p','empty','Čia atsiras tavo šioje naršyklėje sukurti pasiūlymai.'));for(const x of [...workspace.records].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))){const row=el('article','workspace-row');const info=el('div');info.append(el('h3','',x.title),el('p','',money(x)+' · '+x.loc+' · '+(x.status==='active'?'Aktyvus šioje naršyklėje':'Archyvuotas')));const buttons=el('div','workspace-actions');buttons.append(action('Redaguoti','edit',x.id),action(x.status==='active'?'Archyvuoti':'Atkurti','archive',x.id),action('Pašalinti','delete',x.id));row.append(info,buttons);root.append(row);}}else{if(!workspace.searches.length)root.append(el('p','empty','Išsaugotos paieškos su filtrais atsiras čia.'));workspace.searches.forEach((raw,i)=>{let s;try{s=snapshotFrom(JSON.parse(raw));}catch{s=snapshotFrom({query:raw});}const title=s.query||[V14_CATEGORIES[s.filters.category],s.filters.city].filter(Boolean).join(' · ')||'Išsaugoti filtrai';const row=el('article','workspace-row');const info=el('div');info.append(el('h3','',title),el('p','',[s.filters.city,s.filters.min!==''?'Nuo '+s.filters.min+' €':'',s.filters.max!==''?'Iki '+s.filters.max+' €':''].filter(Boolean).join(' · ')||'Duomenys šioje naršyklėje'));const buttons=el('div','workspace-actions');buttons.append(action('Atidaryti','search',String(i)),action('Pašalinti','remove-search',String(i)));row.append(info,buttons);root.append(row);});}}
function openSpace(tab='saved'){spaceTab=tab;renderSpace();showDialog('#spaceDialog');}
function saveCurrentSearch(){const raw=JSON.stringify({query:view.query,filters:view.filters});if(workspace.searches.includes(raw)){notice('Ši paieška jau išsaugota.');return;}if(commit({...workspace,searches:[raw,...workspace.searches].slice(0,20)})){updateCounts();notice('Užklausa ir filtrai išsaugoti šioje naršyklėje.');}}
function categoryFields(){const type=$('#listingType').value;$('.home-fields').hidden=type!=='home';$('.auto-fields').hidden=type!=='auto';for(const input of $$('.home-fields input'))input.disabled=type!=='home';for(const input of $$('.auto-fields input'))input.disabled=type!=='auto';}
function showEditorError(message){$('#editorError').textContent=message;$('#editorError').hidden=!message;}
function renderImagePreviews(){const root=$('#imagePreviews');root.replaceChildren();editingImages.forEach((src,i)=>{const box=el('div','image-preview');const img=el('img');img.src=src;img.alt='Įkeliama nuotrauka '+(i+1);const b=el('button','','Pašalinti');b.type='button';b.addEventListener('click',()=>{editingImages.splice(i,1);renderImagePreviews();});box.append(img,b);root.append(box);});}
function openEditor(id=null){const x=id?workspace.records.find(r=>r.id===id):null;if(id&&!x)return;if(!id&&workspace.records.length>=50){notice('Demonstracijoje galima išsaugoti iki 50 vietinių pasiūlymų.');return;}if($('#detailDialog').open)$('#detailDialog').close();editingId=id;editSession++;imageBusy=false;$('#editorForm').reset();$('#editorTitle').textContent=id?'Redaguoti pasiūlymą':'Naujas pasiūlymas';$('#listingType').value=x?.type||'items';$('#listingCity').value=x?.loc||'';$('#listingTitle').value=x?.title||'';$('#listingDesc').value=x?.desc||'';$('#listingPrice').value=x?.amount??'';$('#listingUnit').value=x?.unit||'€';$('#listingDistrict').value=x?.district||'';$('#listingRooms').value=x?.rooms??'';$('#listingFloor').value=x?.floor??'';$('#listingYear').value=x?.year??'';$('#listingMileage').value=x?.mileage??'';editingImages=[...(x?.images||[])];$('#saveListing').disabled=false;showEditorError('');categoryFields();renderImagePreviews();showDialog('#editorDialog');$('#listingTitle').focus();}
async function imageToData(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Leidžiami JPG, PNG ir WebP failai iki 5 MB.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw new Error('Nuotrauka per didelės raiškos. Pasirink mažesnę.');const ratio=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Nepavyko apdoroti nuotraukos.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/jpeg',.72);if(data.length>600000)data=canvas.toDataURL('image/jpeg',.5);if(data.length>600000)throw new Error('Sumažinta nuotrauka vis dar per didelė. Pasirink mažesnį failą.');return data;}finally{bitmap.close();}}
async function readImages(){const input=$('#listingImages');const files=Array.from(input.files||[]);input.value='';if(!files.length)return;if(files.length+editingImages.length>3){showEditorError('Galima pridėti daugiausia 3 nuotraukas.');return;}if(imageBusy){showEditorError('Palauk, kol bus paruoštos ankstesnės nuotraukos.');return;}const session=editSession;imageBusy=true;$('#saveListing').disabled=true;showEditorError('');try{const ready=[];for(const file of files)ready.push(await imageToData(file));if(session!==editSession)return;editingImages.push(...ready);renderImagePreviews();}catch(error){if(session===editSession)showEditorError(error.message||'Nepavyko perskaityti nuotraukos.');}finally{if(session===editSession){imageBusy=false;$('#saveListing').disabled=false;}}}
function saveListing(event){event.preventDefault();if(imageBusy){showEditorError('Nuotraukos dar ruošiamos.');return;}if(!$('#editorForm').reportValidity())return;if(editingId&&!workspace.records.some(x=>x.id===editingId)){showEditorError('Šis pasiūlymas jau pašalintas kitame skirtuke. Sukurk naują pasiūlymą.');return;}const previous=workspace.records.find(x=>x.id===editingId);const optional=id=>$(id).disabled||$(id).value===''?null:Number($(id).value);const candidate=v14ValidLocal({id:editingId||'local-'+crypto.randomUUID(),type:$('#listingType').value,title:$('#listingTitle').value,desc:$('#listingDesc').value,loc:$('#listingCity').value,amount:Number($('#listingPrice').value),unit:$('#listingUnit').value,district:$('#listingType').value==='home'?$('#listingDistrict').value:'',rooms:optional('#listingRooms'),floor:optional('#listingFloor'),year:optional('#listingYear'),mileage:optional('#listingMileage'),images:editingImages,status:previous?.status||'active',createdAt:previous?.createdAt||new Date().toISOString()});if(!candidate){showEditorError('Patikrink pavadinimą, aprašymą, vietą ir kainą.');return;}const records=editingId?workspace.records.map(x=>x.id===editingId?candidate:x):[candidate,...workspace.records];if(!commit({...workspace,records})){showEditorError('Įrašas neišsaugotas. Pabandyk pašalinti nuotrauką ir pakartoti.');return;}$('#editorDialog').close();refresh();openSpace('listings');notice(editingId?'Pasiūlymas atnaujintas šioje naršyklėje.':'Pasiūlymas išsaugotas ir įtrauktas į šios naršyklės paiešką.');}
function archiveListing(id){const record=workspace.records.find(x=>x.id===id);if(!record)return;const archived=record.status==='active';const next={...workspace,records:workspace.records.map(x=>x.id===id?{...x,status:archived?'archived':'active'}:x),favorites:archived?workspace.favorites.filter(x=>x!==id):workspace.favorites};if(commit(next)){refresh();notice(archived?'Pasiūlymas archyvuotas ir paslėptas paieškoje.':'Pasiūlymas grąžintas į paiešką.');}}
function askDelete(id){if(!workspace.records.some(x=>x.id===id))return;pendingDelete=id;showDialog('#confirmDialog');}
function deleteListing(){const id=pendingDelete;if(!id)return;if(commit({...workspace,records:workspace.records.filter(x=>x.id!==id),favorites:workspace.favorites.filter(x=>x!==id)})){pendingDelete=null;$('#confirmDialog').close();refresh();notice('Vietinis pasiūlymas pašalintas.');}}
function exportLocal(){const blob=new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=el('a');link.href=url;link.download='telkinys-v14-vietiniai-duomenys.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
for(const [type,name] of Object.entries(V14_CATEGORIES)){const card=el('button','category-card');card.type='button';card.dataset.category=type;card.setAttribute('aria-pressed','false');const symbol=el('span','category-icon');symbol.append(icon(iconNames[type]));const text=el('span');text.append(el('strong','',name),el('small','',{home:'pirkti · nuomoti',auto:'rasti · palyginti',items:'nauja · naudota',services:'rasti specialistą',jobs:'ieškoti darbo',prices:'kainų pavyzdžiai'}[type]));card.append(symbol,text);card.addEventListener('click',()=>{resetSearch();$('#category').value=type;applySearch(true);});$('#categories').append(card);}
document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const close=target.closest('[data-close]');if(close){close.closest('dialog')?.close();return;}if(target.closest('[data-new]')){openEditor();return;}const opening=target.closest('[data-open]');if(opening){if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();openDetail(opening.dataset.open);return;}const b=target.closest('[data-action]');if(!b)return;const id=b.dataset.id;switch(b.dataset.action){case 'favorite':toggleFavorite(id);break;case 'compare':toggleCompare(id);break;case 'edit':openEditor(id);break;case 'archive':archiveListing(id);break;case 'delete':askDelete(id);break;case 'new':openEditor();break;case 'share':share(id);break;case 'search':{const raw=workspace.searches[Number(id)];if(!raw)return;let s;try{s=snapshotFrom(JSON.parse(raw));}catch{s=snapshotFrom({query:raw});}view={...s,limit:6};syncInputs();$('#spaceDialog').close();applySearch(true);break;}case 'remove-search':if(commit({...workspace,searches:workspace.searches.filter((_,i)=>i!==Number(id))})){updateCounts();renderSpace();}break;}});
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();applySearch(true);});$('#filterForm').addEventListener('submit',e=>{e.preventDefault();applySearch();});for(const selector of ['#category','#city','#sort'])$(selector).addEventListener('change',()=>applySearch());let filterTimer;for(const selector of ['#minPrice','#maxPrice'])$(selector).addEventListener('input',()=>{clearTimeout(filterTimer);filterTimer=setTimeout(()=>applySearch(),250);});$('#resetFilters').onclick=resetSearch;$('#clearEmpty').onclick=resetSearch;$('#showMore').onclick=()=>{view.limit+=6;renderResults();};for(const b of $$('[data-query]'))b.onclick=()=>querySearch(b.dataset.query);$('#saveSearch').onclick=saveCurrentSearch;$('#openSpace').onclick=()=>openSpace();$('#mobileSpace').onclick=()=>openSpace();$('#mobileSearch').onclick=()=>{$('#searchForm').scrollIntoView();$('#query').focus();};for(const b of $$('[data-space]'))b.onclick=()=>{spaceTab=b.dataset.space;renderSpace();};$('#openCompare').onclick=renderCompare;$('#clearCompare').onclick=()=>{comparing.clear();refresh();};$('#aboutPreview').onclick=()=>showDialog('#aboutDialog');$('#footerAbout').onclick=()=>showDialog('#aboutDialog');$('#exportLocal').onclick=exportLocal;$('#editorForm').addEventListener('submit',saveListing);$('#listingImages').addEventListener('change',readImages);$('#listingType').addEventListener('change',()=>{categoryFields();$('#listingUnit').value=$('#listingType').value==='services'?'€/val.':$('#listingType').value==='jobs'?'€/mėn. bruto':'€';});$('#confirmDelete').onclick=deleteListing;$('#editorDialog').addEventListener('close',()=>{editSession++;imageBusy=false;});$('#detailDialog').addEventListener('close',()=>{selectedId=null;document.title=baseTitle;const u=new URL(location.href);if(u.searchParams.has('skelbimas')){u.searchParams.delete('skelbimas');history.replaceState(null,'',u);}});
window.addEventListener('popstate',()=>{readRoute();syncInputs();renderResults();const id=new URL(location.href).searchParams.get('skelbimas');if(id)openDetail(id,false);else if($('#detailDialog').open)$('#detailDialog').close();});window.addEventListener('storage',event=>{if(event.key!==V14_STORAGE)return;try{workspace=v14ValidWorkspace(event.newValue?JSON.parse(event.newValue):null);refresh();if($('#editorDialog').open)notice('Vietiniai duomenys atnaujinti kitame skirtuke.');}catch{notice('Kito skirtuko duomenų atnaujinimo perskaityti nepavyko.');}});
const mobile=matchMedia('(max-width:760px)');$('#filterDetails').open=!mobile.matches;mobile.addEventListener('change',e=>$('#filterDetails').open=!e.matches);readRoute();syncInputs();renderResults();updateCompareTray();if(storageProblem)notice(storageProblem);const initialId=new URL(location.href).searchParams.get('skelbimas');if(initialId)openDetail(initialId,false);
