import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import crypto from 'node:crypto';
import vm from 'node:vm';
const dir=path.dirname(fileURLToPath(import.meta.url));
const source=fs.readFileSync(path.join(dir,'../telkinys-deploy/index.html'),'utf8');
const catalogMatch=source.match(/const catalog=(\[[\s\S]*?\n\]);/);
const spriteMatch=source.match(/<svg\b[^>]*class="svg-sprite"[^>]*>[\s\S]*?<\/svg>/);
if(!catalogMatch||!spriteMatch)throw new Error('Expected V13 catalog or icon sprite not found; refusing an incomplete build.');
const originalCatalog=vm.runInNewContext('('+catalogMatch[1]+')',{}, {timeout:1000});
if(!Array.isArray(originalCatalog)||originalCatalog.length!==12)throw new Error('Review the changed source catalog before building.');
const read=name=>fs.readFileSync(path.join(dir,name),'utf8');
const pure=name=>read(name).replace(/^export\s+/gm,'');
const js="(()=>{'use strict';\nconst catalog="+catalogMatch[1]+';\n'+pure('model.mjs')+'\n'+pure('search.mjs')+'\n'+read('app.js')+'\n})();';
new vm.Script(js,{filename:'telkinys-v14.bundle.js'});
if(/<\/script/i.test(js))throw new Error('Unexpected closing script tag in bundle.');
const hash=crypto.createHash('sha256').update(js).digest('base64');
const csp=`default-src 'none'; script-src 'sha256-${hash}'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; font-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'`;
let html=read('shell.html').replace('/* V14_STYLES */',read('style.css')).replace('<!-- V14_SPRITE -->',spriteMatch[0]).replace('/* V14_SCRIPT */',()=>js).replace('<!-- CSP -->',`<meta http-equiv="Content-Security-Policy" content="${csp}"><link rel="icon" type="image/svg+xml" href="./favicon.svg">`);
if(/lake-stage|lake-source|stream-map/.test(html))throw new Error('The removed hero illustration must not be included.');
const out=path.join(dir,'../telkinys-v14-dist');
fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'index.html'),html);
fs.writeFileSync(path.join(out,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 44"><rect width="44" height="44" rx="12" fill="#0f7053"/><path d="M8 11c7 0 7 8 14 11m14-11c-7 0-7 8-14 11m0-16v16m-13 5c8 6 18 6 26 0M13 33c5 4 13 4 18 0" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round"/></svg>');
fs.writeFileSync(path.join(out,'version.json'),JSON.stringify({version:'V14-preview',source:'f97e9321191b132709fa980760aa078ab6f7eaf4',mode:'browser-local-demo',productionReady:false,removedHeroIllustration:true,backendConnected:false},null,2));
fs.writeFileSync(path.join(out,'404.html'),'<!doctype html><html lang="lt"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Puslapis nerastas · Telkinys</title><body><main><h1>Puslapis nerastas.</h1><p>Tai bandomoji Telkinio versija.</p><a href="/">Grįžti į Telkinį</a></main></body></html>');
console.log('V14 preview built:',Buffer.byteLength(html),'bytes. Production V13 source was not changed.');
