(()=>{
 const {E,s,pages,link,button,field,form,submit,notice,panel,empty,heading,badge,date,toast,api,go,modal}=App;
 const stages={new:'Naujas pokalbis',discussing:'Derinamos sąlygos',agreed:'Susitarta',completed:'Bendravimas užbaigtas',closed:'Uždarytas'};
 const appointmentStates={proposed:'Laukia atsakymo',accepted:'Patvirtinta',declined:'Atmesta',cancelled:'Atšaukta'};
 function calendarFile(a,title){const stamp=v=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const escape=t=>String(t).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const end=new Date(new Date(a.starts_at).getTime()+a.duration_minutes*60000);const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Telkinys//Beta Calendar//LT','BEGIN:VEVENT','UID:'+a.id+'@telkinys.lt','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(a.starts_at),'DTEND:'+stamp(end),'SUMMARY:'+escape(title),'DESCRIPTION:'+escape(a.note||'Susitikimas suderintas Telkinyje.'),'STATUS:'+(a.state==='cancelled'?'CANCELLED':a.state==='accepted'?'CONFIRMED':'TENTATIVE'),'END:VEVENT','END:VCALENDAR',''].join('\r\n');App.download('telkinys-susitikimas.ics',ics,'text/calendar;charset=utf-8');}
 App.inboxPane=async()=>{
  const data=await api('inbox');const root=E('section',{class:'stack'},E('div',{class:'section-head'},E('div',{},E('h2',{},'Tavo pokalbiai'),E('p',{class:'muted small-text'},'Susirašinėjimai dėl pasiūlymų ir jų eiga.')),button('Atnaujinti',()=>App.render(false),'btn small')));
  if(!data.threads.length){root.append(empty('Pokalbių dar nėra.','Atverk aktualų pasiūlymą ir parašyk autoriui. Žinutę matys tik pokalbio dalyviai.',link('Rasti pasiūlymą',{},'btn primary')));return root;}
  const filter=field('stage','Pokalbių eiga',[['','Visi'],...Object.entries(stages)],'');const list=E('div',{class:'stack'});
  function show(value=''){list.replaceChildren(...data.threads.filter(x=>!value||x.stage===value).map(t=>E('article',{class:'panel inbox-row'},E('div',{},E('div',{class:'row'},E('strong',{},t.other_name),t.unread?E('span',{class:'badge'},t.unread+' nauj.'):null),E('h3',{},link(t.title,{view:'thread',id:t.id})),E('p',{class:'inbox-preview'},t.last_message||'Naujas pokalbis')),E('div',{},E('span',{class:'badge'},stages[t.stage]),E('p',{class:'inbox-meta'},date(t.updated_at)),link('Atverti',{view:'thread',id:t.id},'btn small')))));if(!list.children.length)list.append(E('p',{class:'muted'},'Šioje eigos grupėje pokalbių nėra.'));}
  filter.querySelector('select').addEventListener('change',e=>show(e.target.value));show();root.append(filter,list);App.onLive=async()=>{if(root.isConnected)await App.render(false);};return root;
 };
 App.calendarPane=async()=>{
  const data=await api('calendar');const root=E('section',{class:'stack'},E('div',{class:'section-head'},E('div',{},E('h2',{},'Suderink laiką, ne dešimt žinučių.'),E('p',{class:'muted small-text'},'Sąraše laikas rodomas Lietuvos laiko zonoje. Pasiūlymus tvirtina kita pokalbio pusė.')),button('Atnaujinti',()=>App.render(false),'btn small')));
  if(!data.appointments.length)root.append(empty('Susitikimų dar nėra.','Pasiūlyk laiką konkrečiame pokalbyje. Kitas dalyvis galės jį patvirtinti arba atmesti.',link('Atverti žinutes',{view:'account',tab:'messages'},'btn primary')));
  else root.append(data.appointments.map(a=>panel(E('div',{class:'row between'},E('h3',{},a.title),E('span',{class:'badge'},appointmentStates[a.state])),E('strong',{},date(a.starts_at)+' · '+a.duration_minutes+' min.'),E('p',{class:'text-wrap muted'},a.note),E('div',{class:'actions'},link('Atverti pokalbį',{view:'thread',id:a.thread_id},'btn small'),button('Į mano kalendorių',()=>calendarFile(a,a.title),'btn small')))));
  return root;
 };
 pages.thread=async p=>{
  const gate=App.requireUser();if(gate){s.afterAuth={...p};return gate;}
  let data=await api('thread',{id:p.id}),allMessages=data.messages,hasOlder=data.hasOlder,clientId=crypto.randomUUID();
  const root=E('section',{},E('div',{class:'page-head'},link('← Visi pokalbiai',{view:'account',tab:'messages'},'back'),E('h1',{},data.partner.name),E('p',{class:'muted'},'Dėl pasiūlymo: ',data.listing.status==='active'?link(data.listing.title,{skelbimas:data.listing.id}):data.listing.title)));
  const messageList=E('div',{class:'chat-messages',role:'log','aria-label':'Pokalbio žinutės','aria-live':'polite'});
  function drawMessages(scroll=false){const previous=messageList.scrollHeight,top=messageList.scrollTop;const nearBottom=previous-top-messageList.clientHeight<100;messageList.replaceChildren(...allMessages.map(m=>E('article',{class:'bubble '+(m.sender_id===s.user.id?'mine':'')},E('small',{},m.sender_id===s.user.id?'Tu':m.sender_name),E('p',{},m.body),E('small',{},date(m.created_at)))));if(scroll||nearBottom)messageList.scrollTop=messageList.scrollHeight;}
  const older=button('Rodyti ankstesnes žinutes',async()=>{const before=allMessages[0]?.created_at;if(!before)return;const prev=messageList.scrollHeight;const result=await api('thread',{id:p.id,before});const ids=new Set(allMessages.map(x=>x.id));allMessages=[...result.messages.filter(x=>!ids.has(x.id)),...allMessages];hasOlder=result.hasOlder;drawMessages();messageList.scrollTop=messageList.scrollHeight-prev;older.hidden=!hasOlder;},'btn small');older.hidden=!hasOlder;
  const sidebar=E('aside',{class:'chat-sidebar stack'});let refreshBusy=false;
  async function refresh(){if(refreshBusy||!root.isConnected)return;refreshBusy=true;try{const next=await api('thread',{id:p.id});if(!root.isConnected)return;data=next;const byId=new Map(allMessages.map(x=>[x.id,x]));for(const m of next.messages)byId.set(m.id,m);allMessages=[...byId.values()].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));drawMessages();if(!sidebar.contains(document.activeElement))drawSidebar();const input=compose.querySelector('textarea');input.disabled=data.blocked;compose.querySelector('button[type=submit]').disabled=data.blocked;blockNotice.hidden=!data.blocked;}finally{refreshBusy=false;}}
  const blockNotice=notice('Šiame pokalbyje žinutės užblokuotos.','warning');blockNotice.hidden=!data.blocked;
  const compose=form([field('body','Tavo žinutė','textarea','',{required:true,minLength:1,maxLength:3000,disabled:data.blocked,placeholder:'Parašyk konkrečiai: kas domina, ką norėtum patikslinti ar kokį laiką siūlai.'}),E('div',{class:'row between'},E('span',{class:'hint'},'Pokalbį mato tik jo dalyviai. Pranešus apie pažeidimą jį gali peržiūrėti moderatorius.'),submit('Siųsti'))],async(fd,_,f)=>{await api('send',{threadId:p.id,body:fd.get('body'),clientId});f.querySelector('textarea').value='';clientId=crypto.randomUUID();await refresh();});compose.classList.add('chat-compose');
  const conversation=E('div',{class:'stack'},E('div',{class:'row between'},E('span',{class:'badge'},'Privatus pokalbis'),button('Atnaujinti',refresh,'btn small')),older,messageList,blockNotice,compose);
  function drawSidebar(){
   const t=data.thread,isSeller=t.seller_id===s.user.id,isMineComplete=isSeller?t.seller_completed:t.buyer_completed;
   const stagesPanel=panel(E('h3',{},'Pokalbio eiga'),E('span',{class:'badge'},stages[t.stage]),E('p',{class:'hint'},'Ši eiga padeda susitarti. Ji nėra mokėjimo ar sutarties patvirtinimas.'));
   if(isSeller)stagesPanel.append(form([field('stage','Būsena',Object.entries(stages).filter(([k])=>k!=='completed'),t.stage==='completed'?'agreed':t.stage),submit('Pakeisti eigą','',false)],async fd=>{await api('thread-stage',{id:p.id,stage:fd.get('stage')});await refresh();}));
   stagesPanel.append(E('div',{class:'actions'},button(isMineComplete?'Tavo pusė pažymėta užbaigta':'Pažymėti bendravimą užbaigtu',async()=>{if(isMineComplete)return;if(!confirm('Pažymėti, kad šį bendravimą užbaigei? Tai leis palikti atsiliepimą, kai patvirtins ir kita pusė.'))return;await api('thread-stage',{id:p.id,stage:'completed'});await refresh();},'btn small',{disabled:isMineComplete})),E('p',{class:'hint'},'Pirkėjo pusė: '+(t.buyer_completed?'užbaigta':'dar nepatvirtinta')+'. Autoriaus pusė: '+(t.seller_completed?'užbaigta':'dar nepatvirtinta')+'.'));
   if(t.buyer_completed&&t.seller_completed&&!data.reviewed)stagesPanel.append(button('Palikti atsiliepimą',()=>{modal('Įvertink bendravimą',form([field('score','Įvertinimas',[['5','5 — puikiai'],['4','4 — gerai'],['3','3 — vidutiniškai'],['2','2 — prastai'],['1','1 — labai prastai']],'5'),field('body','Trumpas komentaras','textarea','',{required:true,minLength:10,maxLength:1000}),submit('Paskelbti atsiliepimą')],async fd=>{await api('review',{threadId:p.id,score:Number(fd.get('score')),body:fd.get('body')});App.$('#dialog').close();await refresh();toast('Atsiliepimas paskelbtas.');}));},'btn small primary wide'));
   const appts=panel(E('h3',{},'Susitikimai'));
   for(const a of data.appointments){const actions=E('div',{class:'actions'});if(a.state==='proposed'&&a.proposer_id!==s.user.id){actions.append(button('Patvirtinti',async()=>{await api('appointment-reply',{id:a.id,state:'accepted'});await refresh();},'btn small primary'),button('Atmesti',async()=>{await api('appointment-reply',{id:a.id,state:'declined'});await refresh();},'btn small'));}if(['proposed','accepted'].includes(a.state))actions.append(button('Atšaukti',async()=>{if(!confirm('Atšaukti šį susitikimą?'))return;await api('appointment-reply',{id:a.id,state:'cancelled'});await refresh();},'btn small'));actions.append(button('Kalendorius',()=>calendarFile(a,data.listing.title),'btn small'));appts.append(E('article',{class:'appointment'},E('span',{class:'badge'},appointmentStates[a.state]),E('h4',{},date(a.starts_at)),E('p',{},a.duration_minutes+' min. · '+(a.note||'Be pastabos')),actions));}
   if(!data.appointments.length)appts.append(E('p',{class:'muted small-text'},'Laikas dar nesuderintas.'));
   appts.append(button('＋ Pasiūlyti laiką',()=>{modal('Pasiūlyk susitikimo laiką',form([field('startsAt','Data ir laikas tavo įrenginio laiko zonoje','datetime-local','',{required:true}),field('durationMinutes','Trukmė, min.','number',30,{required:true,min:15,max:240,step:15}),field('note','Vieta ar papildoma informacija','textarea','',{maxLength:500}),submit('Pasiūlyti laiką')],async fd=>{const dateValue=new Date(fd.get('startsAt'));if(!Number.isFinite(dateValue.getTime()))throw new Error('Pasirink tinkamą datą ir laiką.');await api('appointment',{threadId:p.id,startsAt:dateValue.toISOString(),durationMinutes:Number(fd.get('durationMinutes')),note:fd.get('note')});App.$('#dialog').close();await refresh();toast('Laikas pasiūlytas kitam dalyviui.');}));},'btn small wide'));
   const safety=panel(E('h3',{},'Tavo saugumas'),E('p',{class:'hint'},'Nesiųsk slaptažodžių, atkūrimo kodų ar banko kortelės duomenų. Telkinys šioje beta versijoje nevaldo mokėjimų.'),E('div',{class:'stack'},button(data.blockedByMe?'Atblokuoti žinutes':'Blokuoti vartotoją',async()=>{await api('block',{threadId:p.id,blocked:!data.blockedByMe});await refresh();},'btn small'),button('Pranešti moderatoriui',()=>{modal('Pranešti apie pokalbį',notice('Pateikus pranešimą, moderatorius galės peržiūrėti šį pokalbį.'),form([field('reason','Priežastis','textarea','',{required:true,minLength:10,maxLength:1500}),submit('Pateikti pranešimą')],async fd=>{await api('report',{threadId:p.id,reason:fd.get('reason')});App.$('#dialog').close();toast('Pranešimas perduotas moderatoriui.');}));},'btn small danger')));
   sidebar.replaceChildren(stagesPanel,appts,safety);
  }
  drawMessages(true);drawSidebar();root.append(E('div',{class:'chat-layout'},conversation,sidebar));App.onLive=refresh;return root;
 };
})();
