(()=>{
 const {E,s,pages,link,button,notice,panel,heading}=App;
 const para=text=>E('p',{},text);
 function operator(){const o=s.config?.operator;if(!o)return notice('Operatoriaus kontaktai dar nepateikti. Tai parengiamoji, kvietimais ribojama versija. Nekelk jautrių ar trečiųjų asmenų duomenų. Dėl prieigos kreipkis į tave pakvietusį projekto savininką.','warning');return panel(E('h3',{},'Paslaugos operatorius'),para(o.name),o.businessId?para('Veiklos / įmonės kodas: '+o.businessId):null,para(o.address),E('a',{href:'mailto:'+o.email},o.email));}
 function documentPage(title,parts){return E('article',{class:'narrow panel legal'},heading(title,'Beta dokumentų versija: 2026-10-06'),!s.config?.release?.legalApproved?notice('Projektas: operatorius turi patvirtinti faktinį duomenų tvarkymą ir šiuos dokumentus prieš kviesdamas dalyvius. Tai nėra nepriklausoma teisinės atitikties išvada.','warning'):null,operator(),parts.map(([h,t])=>E('section',{},E('h2',{},h),Array.isArray(t)?t.map(para):para(t))));}
 pages.privacy=async()=>documentPage('Privatumo informacija',[
 ['Kokie duomenys tvarkomi',['Paskyrai naudojamas prisijungimo vardas, viešai rodomas vardas ir slaptažodžio maiša. Prisijungimo vardo nereikia tapatinti su tikru vardu. El. pašto adreso registracija nereikalauja.','Saugomi tavo skelbimai, nuotraukos, išsaugojimai, privačių pokalbių žinutės, susitikimų duomenys, atsiliepimai, pagalbos užklausos ir saugumui būtini techniniai įrašai. Atkūrimo kodą sistema saugo maišos forma; patį kodą turi saugoti tu.']],
 ['Kas matoma viešai','Vieši tik patvirtinti skelbimai, jų nuotraukos, pasirinktas viešas vardas ir atsiliepimai. Juodraščių, privačių pokalbių ir paskyros nustatymų kiti dalyviai nemato. Neviešink tikslaus gyvenamosios vietos adreso ar kitų žmonių kontaktų be pagrindo.'],
 ['Pokalbiai ir moderavimas','Pokalbius mato jų dalyviai. Pateikus pranešimą apie konkretų pokalbį, įgaliotas moderatorius gali peržiūrėti to pokalbio žinutes. Tokia administracinė prieiga registruojama veiksmų žurnale.'],
 ['Tvarkymo paskirtis','Duomenys reikalingi paskyrai, skelbimų paskelbimui, susirašinėjimui, susitikimų derinimui, piktnaudžiavimo prevencijai ir pagalbai. Operatorius prieš viešą paleidimą turi nustatyti ir dokumentuoti taikomus teisinius pagrindus, saugojimo terminus bei duomenų tvarkytojų sutartis.'],
 ['Techniniai paslaugų teikėjai','Svetainės sąsaja talpinama Render. Serverinė dalis ir privati failų saugykla naudojamos per Floot; duomenų bazė — per Floot valdomą Postgres paslaugą. Tai techniniai tvarkymo sluoksniai, o ne pažadas, kad paslaugų teikėjų vietos ar tarptautiniai perdavimai jau teisiškai įvertinti. Juos turi patvirtinti operatorius.'],
 ['Naršyklės saugykla','Prisijungimo sesijos kodas laikomas sessionStorage. Jis reikalingas prisijungimui ir pašalinamas atsijungus. Palyginimo pasirinkimai laikomi atverto puslapio atmintyje. V14 sąsajoje reklaminės sekimo priemonės ir rinkodaros slapukai neįdiegti.'],
 ['Duomenų kopija ir trynimas',['Paskyros nustatymuose galima eksportuoti paskyros tekstinius duomenis ir ištrinti paskyrą patvirtinus slaptažodžiu. Ištrynus paskyrą pašalinami jos skelbimai bei su ja susiję įrašai; tai taip pat paveikia susijusių pokalbių prieinamumą kitai pusei.','Pašalintos nuotraukos iškart neberodomos per svetainės prieigos valdiklį. Jų fizinis išvalymas iš failų saugyklos vykdomas priežiūros veiksmu; trumpalaikė jau išduota nuotraukos nuoroda gali veikti iki minutės. Automatinio valymo grafikas ir atsarginių kopijų saugojimo politika turi būti įjungti bei patikrinti prieš platesnį paleidimą.']],
 ['Tavo teisės ir kreipimasis','Dėl susipažinimo su duomenimis, taisymo, trynimo, tvarkymo apribojimo ar kitų taikomų teisių kreipkis į šiame puslapyje nurodytą operatorių arba pateik privatumo užklausą paskyros pagalbos skiltyje. Taip pat gali kreiptis į kompetentingą duomenų apsaugos priežiūros instituciją.'],
 ['Beta apribojimai','Šioje versijoje nėra mokėjimų apdorojimo, tapatybės dokumentų rinkimo, automatinio el. pašto siuntimo ar išorinio AI modelio. Nekelk tapatybės dokumentų, banko kortelių, prisijungimo kodų ar kitų jautrių duomenų.']
 ]);
 pages.terms=async()=>documentPage('Beta naudojimo taisyklės',[
 ['Kokia tai paslauga','Telkinys beta leidžia kviestiems dalyviams skelbti pasiūlymus, juos rasti ir susisiekti. Šis leidimas nėra mokėjimų, pinigų saugojimo, draudimo, tapatybės ar prekių autentiškumo patikros paslauga.'],
 ['Paskyra ir prieiga','Beta skirta pilnamečiams kviestiems dalyviams. Saugok slaptažodį ir atkūrimo kodą, nesidalink paskyra. Viešai rodomas vardas nėra patvirtintos tapatybės žymė.'],
 ['Skelbimai','Skelbk tik teisėtus, tikrus pasiūlymus, kuriuos turi teisę pateikti. Nurodyk teisingą kainą, jos vienetą, vietovę ir būklę. Naudok tik savo ar teisėtai naudojamas nuotraukas. Nauji ir reikšmingai pakeisti pasiūlymai gali būti peržiūrimi prieš publikavimą.'],
 ['Draudžiamas naudojimas','Draudžiami apgaulingi pasiūlymai, neteisėtos prekės ir paslaugos, vogtos nuotraukos, grasinimai, šlamštas, kitų asmenų duomenų viešinimas be pagrindo bei bandymai prieiti prie svetimų paskyrų. Pažeidimai gali lemti skelbimo sustabdymą ar paskyros blokavimą.'],
 ['Susitarimai tarp dalyvių','Dalyviai patys tikrina pasiūlymą, pardavėją ir sandorio sąlygas. Telkinys šiame etape nepriima mokėjimų ir nežada pirkėjo apsaugos. Susitikimo patvirtinimas kalendoriuje nėra įrodymas, kad sandoris ar mokėjimas įvyko.'],
 ['Atsiliepimai','Atsiliepimą galima palikti, kai abi konkretaus pokalbio pusės pažymi bendravimą užbaigtu. Tai bendravimo atsiliepimas, o ne nepriklausomai patikrinto sandorio patvirtinimas. Neskelbk žinomai neteisingų ar įžeidžiančių teiginių.'],
 ['Moderavimas ir pagalba','Apie skelbimą ar pokalbį galima pranešti iš atitinkamo puslapio. Dėl moderavimo sprendimo ar prieigos problemos kreipkis į operatorių. Sprendimo paaiškinimas gali būti pateikiamas paskyroje.'],
 ['Kaina ir beta ribos','Bazinis skelbimų įkėlimas šiame leidime nemokamas. Mokamų planų ar mokėjimo mygtukų nėra. Beta gali keistis ir turėti trūkumų; saugok svarbių nuotraukų ir susitarimų kopijas. Šios taisyklės nepanaikina privalomų įstatymuose nustatytų teisių.']
 ]);
 pages.about=async()=>E('article',{class:'narrow stack'},heading('Vienas pasiūlymas. Vienas pokalbis.','Telkinys beta sutelkia pagrindinius veiksmus vienoje vietoje.'),panel(E('h2',{},'Kas jau įgyvendinta'),para('Paskyros, tikri skelbimų juodraščiai, moderuojamas publikavimas, filtrai, išsaugojimai, palyginimas, pokalbiai ir susitikimų pasiūlymai.'),link('Peržiūrėti pasiūlymus',{},'btn primary')),panel(E('h2',{},'Kas neįjungta'),para('Mokėjimai, tapatybės patikros, AI modelis, automatiniai el. laiškai ir išorinių parduotuvių kainų agregavimas nėra šios beta funkcijos. Vietoje jų pažadų rodome tik veikiančius veiksmus.')),panel(E('h2',{},'Kaip prisijungti'),para('Dalyvius kviečia projekto savininkas. Paskyrai pasirenkamas vardas ir slaptažodis, o atkūrimo kodas parodomas vieną kartą.'),link('Registruotis su kvietimu',{view:'login',mode:'signup'},'btn')),operator());
 pages.help=async()=>E('article',{class:'narrow stack'},heading('Pagalba','Pradėk nuo konkretaus klausimo — taip lengviau jį išspręsti.'),operator(),panel(E('h2',{},'Paskyros užklausa'),para('Prisijungęs gali pateikti pagalbos ar privatumo užklausą. Atsakymas pasirodys toje pačioje skiltyje ir paskyros pranešimuose.'),link('Atverti pagalbą paskyroje',{view:'account',tab:'support'},'btn primary')),panel(E('h2',{},'Pamiršai slaptažodį?'),para('Panaudok registruojantis išsaugotą atkūrimo kodą. Jo netekus automatinio atkūrimo el. paštu šioje beta versijoje nėra.'),link('Atkurti paskyrą',{view:'login',mode:'recover'},'btn')),panel(E('h2',{},'Pastebėjai pažeidimą?'),para('Skelbimo puslapyje arba konkrečiame pokalbyje pasirink „Pranešti moderatoriui“. Nesiųsk slaptažodžių ar bankinių kodų nei dalyviams, nei pagalbai.')));
})();
