import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {v14Search,v14ParseQuery,v14Normalize} from './search.mjs';
import {v14PrepareCatalog,v14ValidLocal,v14ValidWorkspace} from './model.mjs';
const source=fs.readFileSync(new URL('../telkinys-deploy/index.html',import.meta.url),'utf8');
const match=source.match(/const catalog=(\[[\s\S]*?\n\]);/);
assert.ok(match,'V13 catalog exists');
const rows=v14PrepareCatalog(vm.runInNewContext('('+match[1]+')',{}, {timeout:1000}));
const ids=(q,f={})=>v14Search(rows,q,f).items.map(x=>x.id);
const valid={id:'local-12345678-1234-1234-1234-123456789abc',type:'items',title:'Miesto dviratis',desc:'Tvarkingas naudotas miesto dviratis.',loc:'Vilnius',amount:150,unit:'€',images:[],status:'active',createdAt:'2026-10-06T10:00:00Z'};
test('keeps 12 labeled examples and strips fictional trust facts',()=>{assert.equal(rows.length,12);assert.ok(rows.every(x=>x.demo&&!x.own));assert.equal(rows.find(x=>x.id==='s1').facts.Reitingas,undefined);});
test('two rooms + district + price returns only the matching apartment',()=>assert.deepEqual(ids('2 kambarių butas Žirmūnuose iki 180 000 €'),['h1']));
test('Audi search does not substitute Toyota or apartments',()=>assert.deepEqual(ids('Audi iki 10 000 €'),[]));
test('Toyota below 25k returns exactly the two Toyota examples',()=>assert.deepEqual(ids('Toyota RAV4 iki 25k'),['a1','a2']));
test('numeric upper filter excludes a more expensive model',()=>assert.deepEqual(ids('Toyota RAV4',{max:'24000'}),['a2']));
test('incompatible category filter returns no false matches',()=>assert.deepEqual(ids('Toyota RAV4',{category:'home'}),[]));
test('city filter is a hard restriction',()=>assert.deepEqual(ids('Toyota RAV4 Kaune'),['a1']));
test('manual city filter is a hard restriction',()=>assert.deepEqual(ids('',{city:'Klaipėda'}),['i1']));
test('price ascending genuinely changes result order',()=>assert.deepEqual(ids('Toyota RAV4',{sort:'price-asc'}),['a2','a1']));
test('price descending genuinely changes result order',()=>assert.deepEqual(ids('Toyota RAV4',{sort:'price-desc'}),['a1','a2']));
test('newest sorts by stored example timestamps',()=>assert.deepEqual(ids('Toyota RAV4',{sort:'newest'}),['a2','a1']));
test('service keywords, city and inclusive price bound work',()=>assert.deepEqual(ids('Elektrikas Vilniuje iki 40 €'),['s1','s2']));
test('decimal bounds work without string sorting',()=>assert.deepEqual(ids('',{category:'services',min:'35.5'}),['s2']));
test('year and mileage constraints compose with model matching',()=>assert.deepEqual(ids('Toyota RAV4 nuo 2021 m. iki 90 tūkst km'),['a1']));
test('year-looking prices stay prices when followed by euros',()=>{const p=v14ParseQuery('iPhone nuo 2021 €');assert.equal(p.min,2021);assert.equal(p.minYear,null);});
test('not first floor is checked against structured floor data',()=>assert.deepEqual(ids('2 kamb butas ne 1 aukštas'),['h1']));
test('an impossible budget gives a genuine empty state',()=>assert.deepEqual(ids('butas iki 100 000 €'),[]));
test('unknown words do not return arbitrary category examples',()=>assert.deepEqual(ids('zzqxnenumatytas'),[]));
test('numeric product capacity is not silently discarded',()=>assert.deepEqual(ids('iPhone 256 GB',{category:'items'}),['i1']));
test('time requirements are explicitly marked as unsupported',()=>assert.ok(v14Search(rows,'Elektrikas rytoj Vilniuje').warnings.length>0));
test('Lithuanian diacritics are normalized',()=>assert.equal(v14Normalize('ŽIRMŪNAI'),'zirmunai'));
test('valid local listing is accepted',()=>assert.equal(v14ValidLocal(valid).title,'Miesto dviratis'));
test('archived local listings disappear from search',()=>assert.equal(v14Search([{...v14ValidLocal(valid),status:'archived'}],'dviratis').items.length,0));
test('new local listing participates in the same search',()=>assert.equal(v14Search([...rows,v14ValidLocal(valid)],'dviratis Vilniuje iki 200 €').items[0]?.id,valid.id));
test('stored HTML remains plain text, not template markup',()=>{const x=v14ValidLocal({...valid,title:'<img src=x onerror=alert(1)>'});assert.equal(x.title,'<img src=x onerror=alert(1)>');});
test('SVG and non-image URLs are rejected for stored images',()=>assert.deepEqual(v14ValidLocal({...valid,images:['javascript:alert(1)','data:image/svg+xml;base64,PHN2Zz4=']}).images,[]));
test('malformed and invalid-price records are discarded',()=>{assert.equal(v14ValidLocal({...valid,amount:NaN}),null);assert.equal(v14ValidLocal({...valid,id:'not-a-local-id'}),null);assert.equal(v14ValidWorkspace({records:[null,valid,{...valid,amount:-1}]}).records.length,1);});
test('local storage can hold a complete query and filters snapshot',()=>{const s=JSON.stringify({query:'Butas Žirmūnuose '.repeat(12),filters:{category:'home',city:'Vilnius',min:'100000',max:'180000',sort:'newest'}});assert.ok(s.length>250);assert.equal(v14ValidWorkspace({searches:[s]}).searches.length,1);});
test('malformed workspace shapes fall back without crashing',()=>assert.deepEqual(v14ValidWorkspace({favorites:{bad:true},searches:null,records:'bad'}),{version:1,records:[],favorites:[],searches:[]}));
