(()=>{
 'use strict';
 const {E,s,pages,link,button,field,form,submit,notice,panel,heading,date,toast,api,go,modal}=App;
 const refresh=()=>App.render(false);
 const paragraph=t=>E('p',{},t);
 function signedDownload(url,label){const u=new URL(url);if(u.protocol!=='https:'||!u.hostname.endsWith('.amazonaws.com'))throw new Error('Netinkama privati nuoroda.');return E('a',{href:url,target:'_blank',rel:'noopener noreferrer',class:'btn',referrerpolicy:'no-referrer'},label);}
 function passwordAction(title,explanation,action){modal(title,notice(explanation,'warning'),form([field('password','Dabartinis slaptažodis','password','',{required:true,maxLength:128,autocomplete:'current-password'}),submit('Patvirtinti')],async fd=>{const password=String(fd.get('password'));await action(password);}));}
 async function longRequest(op,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),650000);try{const response=await fetch(App.API,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({op,...data,token:s.token}),signal:controller.signal,cache:'no-store',credentials:'omit'});const result=await response.json();if(!response.ok){const error=new Error(result.error||'Veiksmas nepavyko.');error.code=result.code;throw error;}return result;}finally{clearTimeout(timer);}}
 const previousAccount=pages.account;
 pages.account=async p=>{const root=await previousAccount(p);if(s.user){const nav=E('nav',{class:'v16-tools','aria-label':'Paskyros saugumas ir priežiūra'},link('Saugumas ir prisijungimai',{view:'security'},'btn small'),link('Skelbimų aktualumas',{view:'inventory-status'},'btn small'),s.user.role==='admin'?link('Sistemos priežiūra',{view:'operations'},'btn small'):null);root.insertBefore(nav,root.children[1]||null);}return root;};
 pages.security=async()=>{
  const gate=App.requireUser();if(gate)return gate;
  const data=await api('sessions-list');
  const root=E('div',{class:'narrow stack'},heading('Tavo paskyros saugumas','Valdyk aktyvius prisijungimus ir neprarask atkūrimo galimybės.'),notice('Nerodome spėjamo įrenginio ar vietos. Žemiau — tikri sesijų sukūrimo ir galiojimo duomenys.'),panel(E('h2',{},'Aktyvūs prisijungimai'),data.sessions.map(session=>E('article',{class:'v16-session'},E('div',{},E('strong',{},session.current?'Šis prisijungimas':'Kitas prisijungimas'),E('p',{class:'hint'},'Sukurta '+date(session.created_at)),E('p',{class:'hint'},'Galioja iki '+date(session.expires_at))),button(session.current?'Atsijungti čia':'Atjungti',async()=>{if(!confirm(session.current?'Atsijungti iš šios paskyros?':'Atjungti pasirinktą prisijungimą?'))return;const r=await api('session-revoke',{id:session.id});if(r.current){App.setToken('');s.user=null;s.me=null;App.updateHeader();go({view:'login'});}else{toast('Prisijungimas atjungtas.');await refresh();}},'btn small')))),panel(E('h2',{},'Atjunk visus kitus prisijungimus'),paragraph('Šis prisijungimas liks aktyvus. Veiksmui patvirtinti reikės dabartinio slaptažodžio.'),button('Atjungti kitus prisijungimus',()=>passwordAction('Atjungti kitus prisijungimus?','Visuose kituose languose ir įrenginiuose reikės prisijungti iš naujo.',async password=>{await api('sessions-revoke-others',{password});App.$('#dialog').close();await refresh();}),'btn')),panel(E('h2',{},'Atkūrimo kodas'),paragraph('Registruojantis parodytas kodas nėra viešas kvietimo kodas. Saugok jį slaptažodžių tvarkyklėje. Pakeitus slaptažodį gausi naują atkūrimo kodą.'),E('div',{class:'actions'},link('Pakeisti slaptažodį',{view:'account',tab:'profile'},'btn'),link('Pagalba be prisijungimo',{view:'access',kind:'help'},'btn'))));
  return root;
 };
 pages['inventory-status']=async()=>{
  const gate=App.requireUser();if(gate)return gate;const data=await api('my-listings');
  return E('div',{class:'narrow stack'},heading('Aktualūs pasiūlymai, ne seni pažadai.'),notice('Patvirtintas skelbimas paieškoje rodomas 30 dienų nuo paskutinio aktualumo patvirtinimo. Pasibaigus laikui jis nedingsta iš paskyros. Pakartotinai patvirtink tik tikrai galiojantį pasiūlymą.'),data.items.length?data.items.map(item=>panel(E('h2',{},item.title),E('span',{class:'badge'},App.statuses[item.status]||item.status),E('p',{class:'hint'},item.validUntil?'Aktualumo galiojimas: '+date(item.validUntil):'Aktualumo laikas dar nenurodytas'),item.status==='active'&&new Date(item.validUntil).getTime()<Date.now()?notice('Paieškoje paslėptas, kol patvirtinsi aktualumą.','warning'):null,E('div',{class:'actions'},item.status==='active'?button('Pasiūlymas dar aktualus',async()=>{await api('listing-confirm',{id:item.id});toast('Aktualumas patvirtintas 30 dienų.');await refresh();},'btn primary'):null,link('Redaguoti',{view:'edit',id:item.id},'btn')))):panel(E('h2',{},'Dar neturi skelbimų.'),link('Įkelti pirmą pasiūlymą',{view:'edit'},'btn primary')));
 };
 pages.operations=async()=>{
  const gate=App.requireUser();if(gate)return gate;if(s.user.role!=='admin')return panel(heading('Ši skiltis skirta administratoriui.'),link('Grįžti į paskyrą',{view:'account'},'btn'));
  const [data,readiness]=await Promise.all([api('backup-status'),api('readiness')]);
  const latest=data.copies[0],fresh=!!latest?.restore_verified_at&&Date.now()-new Date(latest.created_at).getTime()<36*3600000;
  const root=E('div',{class:'stack v16-operations'},heading('Sistemos priežiūra','Kopijos, atkūrimo patikra ir aiškiai matomos paleidimo kliūtys.'),notice(fresh?'Naujausia kopija sukurta ir jos atkūrimas patvirtintas atskiroje PostgreSQL aplinkoje.':'Nėra neseniai patvirtintos kopijos. Patikrink paskutinio priežiūros darbo rezultatą.',fresh?'':'warning'));
  root.append(E('div',{class:'v16-grid'},panel(E('h2',{},'Automatinės kopijos'),paragraph(data.automaticSchedule),paragraph('Kopijos saugomos privačiai. Numatyta 14 dienų rotacija; paskutinė patikrinta kopija nesunaikinama vien todėl, kad naujesnių sukurti nepavyko.'),paragraph(data.scope),E('div',{class:'actions'},button('Atnaujinti būseną',refresh,'btn primary'),button('Sukurti papildomą kopiją',()=>passwordAction('Sukurti privačią kopiją?','Bus kopijuojami paskyrų duomenys ir paruoštos nuotraukos. Tai gali užtrukti. Rankinė kopija savaime nėra patvirtintas atkūrimo bandymas.',async password=>{await longRequest('backup-create',{password});App.$('#dialog').close();await refresh();}),'btn'))),panel(E('h2',{},'Priežiūros eilė'),E('p',{class:'v16-number'},String(data.queue.due)),paragraph('failų laukia numatyto pašalinimo. Iš viso eilėje: '+data.queue.waiting+'.'),paragraph('Šalinami tik jau į eilę įtraukti failai, kurių laukimo terminas pasibaigė. Taip pat valomos pasibaigusios anoniminės užklausos ir sesijos.'),button('Vykdyti priežiūrą dabar',()=>passwordAction('Vykdyti numatytą priežiūrą?','Bus pašalinti tik pasibaigę ir jau suplanuoti techniniai įrašai. Aktyvūs skelbimai ir pokalbiai nešalinami.',async password=>{await api('operations-run',{password});App.$('#dialog').close();await refresh();}),'btn'))));
  root.append(panel(E('h2',{},'Kopijų istorija'),data.copies.length?data.copies.map(copy=>E('article',{class:'v16-session'},E('div',{},E('strong',{},date(copy.created_at)),E('p',{class:'hint'},copy.restore_verified_at?'Atkūrimas patikrintas '+date(copy.restore_verified_at):'Atkūrimas dar nepatvirtintas'),E('p',{class:'hint'},'Duomenų eilučių: '+(copy.row_count??0))),button('Privati kopija',()=>passwordAction('Atverti privačios kopijos nuorodas?','Kopijoje yra jautrių paskyros duomenų, įskaitant slaptažodžių maišas. Neskelbk jos viešai ir nekelk į pokalbį. Nuorodos trumpalaikės.',async password=>{const r=await api('backup-download',{id:copy.id,password});modal('Privati kopija',notice('Nuorodos galioja trumpai. Saugok atsisiųstus failus privačiai. Kopiją atkurk tik patikrintoje aplinkoje.','warning'),signedDownload(r.url,'Duomenų kopija JSON'),E('div',{class:'stack'},r.files.map((f,i)=>signedDownload(f.url,'Nuotraukos kopija '+(i+1)))));}),'btn small'))):paragraph('Kopijų dar nėra.')));
  root.append(panel(E('h2',{},'Pasirengimas platesniam naudojimui'),E('div',{class:'v16-checks'},readiness.checks.map(check=>E('div',{class:'v16-check'},E('span',{class:'v16-state '+(check.ready?'ready':'pending')},check.ready?'Patvirtinta':'Reikia veiksmo'),E('span',{},check.name)))),paragraph(readiness.note),E('div',{class:'actions'},link('Operatoriaus duomenys',{view:'account',tab:'admin'},'btn'),link('Privatumo informacija',{view:'privacy'},'btn'))));
  root.append(panel(E('h2',{},'AI juodraščių prieiga'),paragraph('AI padeda perrašyti tik paties vartotojo pasirinktą poreikio tekstą. Jis nepateikia pardavėjų, kainų ar laisvų laikų. Integracija parengta ribotam bandymui; prieš įjungdamas kitiems dalyviams patikrink rezultatus ir duomenų tvarkymo informaciją.'),paragraph('Naudojamas gpt-6-luna per Floot. Už užklausas naudojami Floot kreditai; ribojama iki 5 vienam vartotojui ir 30 projektui per dieną.'),link('Išbandyti su neasmeniniu tekstu',{view:'need-new'},'btn'),form([E('label',{class:'checkline'},E('input',{type:'checkbox',name:'enabled',checked:s.config?.features?.aiDrafts===true}),E('span',{},'Įjungti AI juodraščius beta dalyviams')),E('label',{class:'checkline'},E('input',{type:'checkbox',name:'reviewed'}),E('span',{},'Patikrinau integraciją ir peržiūrėjau AI duomenų perdavimo informaciją.')),submit('Išsaugoti AI prieigą')],async fd=>{await api('ai-settings',{enabled:fd.has('enabled'),reviewed:fd.has('reviewed')});s.config=await App.get({op:'config'});toast('AI prieiga atnaujinta.');await refresh();})));
  return root;
 };
 const oldNeedNew=pages['need-new'];
 pages['need-new']=async p=>{
  const root=await oldNeedNew(p);if(!s.user||!(s.user.role==='admin'||s.config?.features?.aiDrafts))return root;
  const scope=root.querySelector('[name=scope]'),title=root.querySelector('[name=title]');if(!scope||!title)return root;
  const consent=E('input',{type:'checkbox'}),state=E('p',{class:'hint','aria-live':'polite'}),preview=E('div',{class:'stack'});
  const ai=E('details',{class:'panel v16-ai'},E('summary',{},'Padėti aiškiau aprašyti poreikį · AI juodraštis'),paragraph('Pasirinktinai: išsiųsime tik aukščiau įrašytą darbų aprašymą AI teikėjui per Floot. Pašalink adresus, kontaktus ir kitus asmens duomenis. Rezultatą turėsi pats peržiūrėti.'),E('label',{class:'checkline'},consent,E('span',{},'Sutinku išsiųsti šį aprašymą AI juodraščiui parengti.')),button('Parengti juodraštį',async()=>{
   if(!consent.checked){state.textContent='Pirma patvirtink, kokį tekstą siųsime.';return;}
   if(scope.value.trim().length<15||scope.value.length>1500){state.textContent='AI juodraščiui reikia 15–1500 simbolių aprašymo.';return;}
   state.textContent='Rengiamas juodraštis…';preview.replaceChildren();
   try{const result=await api('ai-draft',{draft:{text:scope.value,consent:true}});const draft=result.suggestion;state.textContent='Peržiūrėk tekstą. Nieko nepaskelbėme ir formos nepakeitėme.';preview.append(E('h3',{},draft.title),E('p',{class:'text-wrap'},draft.scope),draft.questions.length?E('div',{},E('strong',{},'Dar reikėtų patikslinti:'),draft.questions.map(q=>E('p',{},q))):null,button('Naudoti šį juodraštį',()=>{title.value=draft.title;scope.value=draft.scope;scope.dispatchEvent(new Event('input',{bubbles:true}));preview.replaceChildren();state.textContent='Juodraštis perkeltas į formą. Patikslink sąlygas ir išsaugok pats.';},'btn primary'));}
   catch(error){state.textContent=error.code==='OUT_OF_CREDITS'?'AI šiuo metu nepasiekiamas. Aprašymą gali tęsti pats.':error.message;}
  },'btn'),state,preview);
  root.append(ai);return root;
 };
 function operator(){const o=s.config?.operator;return o?panel(E('h2',{},'Paslaugos operatorius'),paragraph(o.name),o.businessId?paragraph('Veiklos kodas: '+o.businessId):null,paragraph(o.address),E('a',{href:'mailto:'+o.email},o.email)):notice('Operatoriaus rekvizitai dar nepatvirtinti. Tai uždara bandomoji aplinka. Nekelk jautrių duomenų; dėl prieigos ar privatumo pateik užklausą viešoje pagalbos skiltyje.','warning');}
 pages.privacy=async()=>E('article',{class:'narrow stack legal'},heading('Privatumo informacija','V16 techninio veikimo aprašas · 2026-10-08'),operator(),!s.config?.release?.legalApproved?notice('Prieš platesnį dalyvių kvietimą operatorius turi patvirtinti tikrus rekvizitus, tvarkymo pagrindus, saugojimo terminus ir paslaugų teikėjų sutartis. Tai nėra nepriklausoma teisinės atitikties išvada.','warning'):null,
  panel(E('h2',{},'Paskyra ir privatūs duomenys'),paragraph('Naudojamas prisijungimo vardas, pasirinktas viešas vardas ir slaptažodžio maiša. El. pašto adreso registracija nereikalauja. Saugomi skelbimai, nuotraukos, žinutės, poreikiai, specialistų atsakymai, susitarimai, susitikimai, pagalbos užklausos ir techniniai saugumo įrašai. Viešai rodomas vardas nėra tapatybės patvirtinimas.'),paragraph('Sesijos kodas laikomas šio lango sessionStorage, pašalinamas atsijungus ir nustoja veikti pasibaigus jo terminui. Aktyvius prisijungimus gali valdyti paskyros saugumo skiltyje. Reklaminis sekimas svetainės sąsajoje neįdiegtas.')),
  panel(E('h2',{},'Kas ką mato'),paragraph('Viešas katalogas rodo patvirtintus, dar aktualius skelbimus. Juodraščius mato savininkas ir pagal pareigas peržiūrintys moderatoriai. Poreikį po peržiūros gali skaityti atitinkamą paslaugą ir miestą pasirinkę specialistai. Konkretaus pasiūlymo kainą, žinutes ir susitarimą mato jo dalyviai. Pateikus pranešimą apie konkretų pokalbį, įgalioto moderatoriaus peržiūra registruojama. Kontaktų ir tikslių adresų į viešą aprašymą nekelk.')),
  panel(E('h2',{},'Pasirinktinis AI juodraštis'),paragraph('AI juodraščiai beta dalyviams iš pradžių išjungti. Administratoriui juos įjungus, AI užklausa siunčiama tik paspaudus mygtuką ir sutikus perduoti pasirinktą tekstą. Per Floot perduodamas tik įvestas darbų aprašymas modeliui gpt-6-luna; paskyros įrašai, pokalbių istorija ir kontaktai automatiškai nesiunčiami. Pašalink asmens duomenis prieš siųsdamas. Modelio tekstą būtina patikrinti; jis nieko nepaskelbia, neužsako ir nesudaro susitarimo už tave.'),paragraph('AI teikėjo sąlygas, duomenų saugojimą ir galimus tarptautinius perdavimus operatorius turi įvertinti prieš įjungdamas funkciją dalyviams. Tikslių teikėjo saugojimo terminų ši beta nežada.')),
  panel(E('h2',{},'Kopijos ir techninė priežiūra'),paragraph('Numatytas kasdienis privačių duomenų kopijų ir paruoštų nuotraukų kopijavimas. Kopijos saugomos privačioje Floot saugykloje. GitHub Actions laikinoje, izoliuotoje PostgreSQL aplinkoje atliekamas atkūrimo ir vientisumo patikrinimas. Duomenų kopijos, jų turinys ir prieigos kodai nekeliami į viešus GitHub failus, žurnalus ar priedus. Įprasta kopijų rotacija — 14 dienų; paskutinė patikrinta kopija gali likti ilgiau, jei naujesnės patvirtintos kopijos nėra. Grafikas gali vėluoti ar nepavykti; administratoriui rodoma tikra paskutinio darbo būsena.'),paragraph('Iš pagrindinės sistemos pašalinti duomenys gali išlikti anksčiau sukurtose kopijose iki jų rotacijos. Tai nėra pažadas apie nepriklausomą atsarginio teikėjo saugyklą. Kopijose neatkuriamos prisijungimo sesijos, kvietimai ir laikini prieigos įrašai.')),
  panel(E('h2',{},'Pagalba be prisijungimo'),paragraph('Galima pateikti užklausą nenurodant el. pašto ar telefono. Vieną kartą parodytas atsitiktinis kodas suteikia prieigą prie tos užklausos, atsakymo ir pašalinimo. Sistemoje laikoma kodo maiša. Prieiga galioja 30 dienų; pasibaigusius įrašus šalina priežiūra. Automatiniai el. laiškai dar nesiunčiami.')),
  panel(E('h2',{},'Eksportas ir pašalinimas'),paragraph('Paskyroje gali eksportuoti savo tekstinius duomenis bei susitarimus ir paprašyti paskyros pašalinimo. Pašalinimas gali paveikti susijusių pokalbių bei susitarimų prieinamumą kitai pusei, todėl prieš tai pasiimk svarbias kopijas. Nuotraukų prieiga per svetainę uždaroma pašalinus įrašą; jau išduota privati nuoroda gali veikti iki minutės. Fizinis failo šalinimas vykdomas per numatytą priežiūros eilę po laukimo termino.'),link('Privatumo užklausa be prisijungimo',{view:'access',kind:'privacy'},'btn primary')),
  panel(E('h2',{},'Techniniai paslaugų teikėjai ir ribos'),paragraph('Svetainės sąsaja talpinama Render, API ir privati saugykla — Floot, duomenų bazė — Floot valdomoje PostgreSQL paslaugoje. GitHub naudojamas kodo ir automatinių techninių patikrų vykdymui. Duomenys tvarkomi paskyrai, skelbimams, susirašinėjimui, pagalbai ir saugumui užtikrinti. Operatorius turi dokumentuoti teisinius pagrindus, duomenų saugojimo politiką, tvarkytojų sutartis ir duomenų teisių įgyvendinimą. Mokėjimai, tapatybės dokumentų rinkimas ir el. pašto siuntimas šiame leidime neįjungti.')));
 const oldAbout=pages.about;pages.about=async p=>{const root=await oldAbout(p);for(const el of root.querySelectorAll('p'))if(el.textContent.includes('AI modelis, kainų agregavimas'))el.textContent='Mokėjimai, tapatybės ir kvalifikacijos patikros, kainų agregavimas, automatiniai el. laiškai ir visų kategorijų projektai dar neįjungti. Pasirinktinis AI juodraštis parengtas administratoriaus bandymui; dalyviams jis prieinamas tik atskirai įjungus. Specialistų pasiūlos ir atsakymo termino negarantuojame.';root.append(panel(E('h2',{},'Paskyros saugumas ir pasiūlymų aktualumas'),paragraph('V16 gali valdyti prisijungimo sesijas ir patvirtinti, kad skelbimas dar aktualus. Poreikio susitarimo sąlygos po pasirinkimo nekinta. Techninės priežiūros skiltyje administratorius mato kopijų ir atkūrimo patikros būseną.'),link('Kas naujo V16',{view:'changes'},'btn')));return root;};
 const oldTerms=pages.terms;pages.terms=async p=>{const root=await oldTerms(p);for(const paragraph of root.querySelectorAll('p'))if(paragraph.textContent.includes('tai nėra pažadas apie jau įjungtą automatinį valymą'))paragraph.textContent='Viešos pagalbos prieigos kodas galioja 30 dienų. Pasibaigusias užklausas šalina automatinė arba rankinė techninė priežiūra; jos būsena matoma administratoriui.';root.append(panel(E('h2',{},'V16 papildymas'),paragraph('Skelbimo aktualumą patvirtina jo autorius kas 30 dienų. AI pateiktas tekstas yra tik pasirinktinis juodraštis, ne patikrintas faktas ar Telkinio garantija. Prieš skelbdamas visada peržiūrėk savo sąlygas. Susitarimo kopijos patvirtinimas nėra mokėjimo, tapatybės ar atliktų darbų kokybės patikra.'),link('Atnaujinta privatumo informacija',{view:'privacy'},'btn')));return root;};
 pages.changes=async()=>E('div',{class:'narrow stack'},heading('V16 · patikimesnis pagrindas'),panel(E('h2',{},'Daugiau kontrolės tavo paskyroje'),paragraph('Aktyvių prisijungimų sąrašas, jų atjungimas ir skelbimų aktualumo patvirtinimas. Poreikio susitarimą galima atšaukti ir užblokavus bendravimą.'),link('Mano paskyra',{view:'account'},'btn primary')),panel(E('h2',{},'Privatūs susitarimai ir priežiūra'),paragraph('Susitarimo sąlygas nuo pakeitimų saugo ir duomenų bazė. Administratorius mato privačių kopijų, atkūrimo patikrų ir suplanuoto failų valymo būseną.')),panel(E('h2',{},'Beta ribos išlieka'),paragraph('Mokėjimai, tapatybės patikros ir automatinis el. paštas dar neįjungti. AI juodraštis parengtas atskiram bandymui, o ne naudojamas kaip automatinė paieškos ar sandorio garantija. Tikrą pasiūlą kuria dalyviai, ne demonstraciniai duomenys.'),E('div',{class:'actions'},link('Prašyti kvietimo',{view:'access',kind:'invite'},'btn'),link('Pagalba',{view:'help'},'btn'))));
 const footer=document.querySelector('footer nav');if(footer)footer.append(link('Kas naujo V16',{view:'changes'}));
})();
