// Generated by scripts/build-public-assets.mjs. Public assets only.
export const publicAssets=["app.5536c833642b.js","crawler.0688500bc73f.js","counter.86242e1dc9d9.js","mottos.daa44e0e588b.js","hologram.80648a5c2559.js","styles.686cb88e0595.css","mottos.7ab60957cb05.css"];
