// Generated by scripts/build-public-assets.mjs. Public assets only.
export const publicAssets=["app.5536c833642b.js","crawler.0688500bc73f.js","counter.0b9a6405dc8d.js","mottos.daa44e0e588b.js","hologram.4a840285ff24.js","styles.686cb88e0595.css","mottos.7ab60957cb05.css","experience.af9508f5d872.js","mobile-performance.5a82cd7a17d9.css"];
